import {describe,it,expect} from 'vitest';
import {Simulation,type Packet} from '../src/sim';
import {ACTIVES,BOSS_WAVES,BUFFS,ENEMIES,HP_SCALE,DMG_SCALE,KEYS,MINION_REWARD_DROP_CHANCE,MORTAR_TARGET_CAP,SIZE,TOTAL_WAVES,TOWERS,WAVE_BATCHES,WAVES,type ActiveKind} from '../src/data';
import {cell,distance,flow,WorldMap} from '../src/map';
import {CELL_EFFECTS,FIXED_MAP_ROWS,FIXED_VARIANT_ROWS} from '../src/map-layout';
const run=(s:Simulation,seconds:number)=>{for(let i=0;i<Math.round(seconds*30);i++)s.tick(1/30);};
function sandbox(){const s=new Simulation();s.start();s.time=0;s.batches=[];s.god=true;s.addBuilding('arrow',17.5,16.5,true);return s;}
function equip(s:Simulation,kind:ActiveKind,slot=0){s.gear[slot]={id:s.serial++,kind,ready:-100,until:-100};}
const packet=(damage:number):Packet=>({damage,pierce:0,hunter:0,boss:0,overflow:0,source:1,crit:false});
describe('construction and progression',()=>{
 it('starts with an empty site and requires the player to build the first tower',()=>{const s=new Simulation();expect(s.buildings).toHaveLength(0);expect(s.player.gold).toBe(120);expect(s.player.selected).toBe('arrow');});
 it('charges once, preserves interrupted progress, finishes with remaining HP ratio',()=>{const s=sandbox();s.command('build');const t=s.atPlayer()!;expect(s.gold).toBe(80);run(s,.9);const progress=t.progress;s.input.x=1;run(s,.2);expect(s.task).toBeNull();expect(t.progress).toBe(progress);s.input.x=0;s.player.x=t.x;s.player.y=t.y;t.hp=t.maxHp*.5;s.command('build');run(s,2.3);expect(t.progress).toBe(1);expect(t.hp/t.maxHp).toBeCloseTo(.5);expect(s.gold).toBe(80);});
 it('incoming damage does not cancel construction',()=>{const s=sandbox();s.god=false;s.command('build');s.damagePlayer(10);expect(s.task?.type).toBe('build');run(s,.5);expect(s.atPlayer()!.progress).toBeGreaterThan(0);});
 it('repair takes twice the construction time and a full bar costs half the build price',()=>{const s=sandbox();const t=s.buildings[0];s.player.x=t.x;s.player.y=t.y;t.hp=90;s.command('repair');run(s,.5);expect(t.hp).toBeCloseTo(105);expect(s.gold).toBeCloseTo(118.333333);run(s,2.5);expect(t.hp).toBeCloseTo(180);expect(s.gold).toBeCloseTo(110);});
 it('halves ongoing repair speed while an enemy is attacking the worker without canceling repair',()=>{const normal=sandbox(),hit=sandbox(),a=normal.buildings[0],b=hit.buildings[0];for(const [s,t] of [[normal,a],[hit,b]] as const){s.player.x=t.x;s.player.y=t.y;t.hp=90;s.command('repair');}const e=hit.spawn('infantry',{x:b.x+1.1,y:b.y},1);hit.updateEnemies(0);expect(e.target).toBe(hit.player.id);expect(hit.underAttack()).toBe(true);run(normal,.2);run(hit,.2);expect(hit.task?.type).toBe('repair');expect(b.hp-90).toBeCloseTo((a.hp-90)*.5);expect(hit.repairRateFor()).toBeCloseTo(hit.repairRate*.5);e.x=28;e.y=28;hit.projectiles=[];expect(hit.underAttack()).toBe(false);expect(hit.repairRateFor()).toBe(hit.repairRate);});
 it('upgrade keeps HP ratio and attack/skill progress',()=>{const s=sandbox(),t=s.buildings[0];s.player.level=11;s.setGold(1000);s.player.x=t.x;t.hp=90;t.shot=.3;t.skill=.4;s.command('upgrade');expect(t.hp).toBe(130.5);expect(t.maxHp).toBe(261);expect(t.shot).toBe(.3);expect(t.skill).toBe(.4);});
 it('validates river, occupancy and unlock requirements',()=>{const s=sandbox();s.player.x=4.5;s.player.y=9.5;const old=s.buildings.length;s.command('build');expect(s.buildings.length).toBe(old);s.player.x=16.5;s.player.y=16.5;s.selected='mortar';s.command('build');expect(s.buildings.length).toBe(old);s.selected='arrow';s.spawn('infantry',s.player,1);s.command('build');expect(s.buildings.length).toBe(old);});
 it('does not impose a gameplay building-count cap',()=>{const s=new Simulation();s.start();s.player.selected='wall';s.setGold(2000);const sites=[];for(let y=0;y<SIZE&&sites.length<40;y++)for(let x=0;x<SIZE&&sites.length<40;x++)if(s.map.isBuildable(x+.5,y+.5))sites.push({x:x+.5,y:y+.5});for(const p of sites){s.player.x=p.x;s.player.y=p.y;s.command('build');}expect(s.buildings).toHaveLength(40);expect(s.buildings.every(t=>t.owner===s.player.id)).toBe(true);});
 it('uses the context action to build on empty ground and repair a damaged building',()=>{const s=new Simulation();s.start();s.command('context');const t=s.atPlayer()!;expect(t.kind).toBe('arrow');expect(t.owner).toBe(0);t.progress=1;t.maxHp=TOWERS.arrow.hp;t.hp=t.maxHp/2;s.command('context');expect(s.task).toEqual({type:'repair',id:t.id});});
 it('life aura toggling does not heal and uses effective max life for repair',()=>{const s=sandbox(),t=s.buildings[0];t.hp=90;s.buffs.life=1;s.attributes(t);expect(t.hp).toBe(112.5);s.player.x=28;s.attributes(t);expect(t.hp).toBe(90);s.player.x=t.x;s.command('repair');run(s,3.1);expect(t.hp).toBeCloseTo(225);expect(s.gold).toBeCloseTo(110);});
});
describe('equipment / buffs',()=>{
 it('contains every approved reward',()=>{expect(Object.keys(ACTIVES)).toHaveLength(9);expect(Object.keys(BUFFS)).toHaveLength(11);expect(new Simulation().rewardPool).toHaveLength(20);});
 it('full active slots do not stop buff pickup or drop old gear',()=>{const s=sandbox();equip(s,'build');equip(s,'repair',1);s.drop('power',s.player);s.pickup();expect(s.buffs.power).toBe(1);expect(s.gear.map(g=>g?.kind)).toEqual(['build','repair']);expect(s.swap).toBeNull();expect(s.drops).toHaveLength(0);});
 it('swapped gear persists on same tile with cooldown intact',()=>{const s=sandbox();equip(s,'boots');equip(s,'repair',1);s.use(0);const ready=s.gear[0]!.ready;s.drop('build',s.player);s.pickup();expect(s.swap).not.toBeNull();s.exchange(0);expect(s.gear[0]!.kind).toBe('build');expect(s.drops[0].kind).toBe('boots');expect(s.drops[0].gear!.ready).toBe(ready);expect(s.drops[0].gear!.until).toBeLessThan(s.time);s.pickup();s.exchange(0);s.use(0);expect(s.active('boots')).toBe(false);});
 it('ground drops occupy separate tiles without blocking construction',()=>{const s=sandbox();s.drop('power',s.player);s.drop('armor',s.player);expect(new Set(s.drops.map(cell)).size).toBe(2);s.command('build');expect(s.atPlayer()).toBeTruthy();});
 it('construction and repair equipment affect their own rates only',()=>{const s=sandbox();expect(s.repairRate).toBe(.5);equip(s,'build');s.use(0);expect(s.buildRate).toBe(2);expect(s.repairRate).toBe(.5);equip(s,'repair',1);s.use(1);expect(s.repairRate).toBe(1);});
 it('base repair speed stays at half construction speed at every player level',()=>{const s=sandbox();for(let level=1;level<=12;level++){s.player.level=level;expect(s.repairRate).toBeCloseTo(s.buildRate/2);}});
 it('instant repair pays the half-build repair rate, refuses full HP and ignores repair speed',()=>{const s=sandbox(),t=s.buildings[0];s.player.x=t.x;equip(s,'instant');equip(s,'repair',1);s.use(0);expect(s.gear[0]!.ready).toBe(-100);t.hp=100;s.use(1);s.use(0);expect(t.hp).toBeCloseTo(163);expect(s.player.gold).toBeCloseTo(113);});
 it('shield protects scaffold and disappears on unequip',()=>{const s=sandbox();s.command('build');const t=s.atPlayer()!;equip(s,'shield');s.use(0);expect(t.shield).toBeCloseTo(16.2);s.damageBuilding(t,10);expect(t.hp).toBe(54);s.removeGear(s.gear[0]!);expect(t.shield).toBe(0);});
 it('attack-speed effects add and skill resonance remains separate',()=>{const s=sandbox(),t=s.buildings[0];s.buffs.haste=1;s.buffs.resonance=1;equip(s,'overload');s.use(0);s.attributes(t);expect(t.interval).toBeCloseTo(.8/1.8);expect(t.skillInterval).toBeCloseTo(6.8);});
 it('gives ordinary enemies a 0.5 percent reward roll while reserving every boss guarantee',()=>{expect(MINION_REWARD_DROP_CHANCE).toBe(.005);const lucky=sandbox(),luckyEnemy=lucky.spawn('infantry',{x:24,y:24},1),luckyPool=lucky.rewardPool.length;lucky.rand=()=>0;lucky.hitEnemy(luckyEnemy,packet(1000));expect(lucky.rewardPool).toHaveLength(luckyPool-1);const dry=sandbox(),dryEnemy=dry.spawn('infantry',{x:24,y:24},1),dryPool=dry.rewardPool.length;dry.rand=()=>.999;dry.hitEnemy(dryEnemy,packet(1000));expect(dry.rewardPool).toHaveLength(dryPool);const reserved=new Simulation();reserved.start();reserved.rewardPool=reserved.rewardPool.slice(0,6);const minion=reserved.spawn('infantry',{x:24,y:24},1);reserved.rand=()=>0;reserved.hitEnemy(minion,packet(1000));expect(reserved.rewardPool).toHaveLength(6);const bossRun=sandbox(),boss=bossRun.spawn('boss1',{x:24,y:24},3),bossPool=bossRun.rewardPool.length;bossRun.rand=()=>.999;bossRun.hitEnemy(boss,packet(10000));expect(bossRun.rewardPool).toHaveLength(bossPool-1);});
});
describe('enemy and combat behavior',()=>{
 it('a complete tower enclosure triggers real demolition rather than idle pathfinding',()=>{const s=sandbox();s.buildings=[];s.reindex();for(let y=15;y<=17;y++)for(let x=15;x<=17;x++)if(x!==16||y!==16)s.addBuilding('wall',x+.5,y+.5,true);s.spawn('heavy',{x:20.5,y:16.5},1);run(s,45);expect(s.stats.lost).toBeGreaterThan(0);});
 it('a player inside a tower can still be hit by an archer targeting the player',()=>{const s=sandbox();s.god=false;s.player.x=s.buildings[0].x;s.player.y=s.buildings[0].y;const e=s.spawn('archer',{x:20.5,y:16.5},1);s.enemyArrow(e,s.player);s.projectiles[0].target=0;run(s,.45);expect(s.player.hp).toBeLessThan(100);});
 it('weaker slow resumes after a shorter strong slow expires',()=>{const s=sandbox();const e=s.spawn('heavy',{x:24.5,y:24.5},1);s.slow(e,.35,3);s.slow(e,.5,1);run(s,.5);expect(e.slow).toBe(.5);run(s,.7);expect(e.slow).toBe(.65);});
 it('limits each mortar blast to the target cap of its firing level',()=>{for(const level of [1,4]){const s=sandbox();s.buildings=[];s.enemies=[];s.reindex();const t=s.addBuilding('mortar',10.5,10.5,true);t.level=level;s.attributes(t);const points=[];for(let y=-2;y<=2;y++)for(let x=-2;x<=2;x++)if(Math.hypot(x*.55,y*.55)<=1.25)points.push({x:16.5+x*.55,y:16.5+y*.55});const targets=points.map(p=>s.spawn('infantry',p,1));s.rebuildBuckets();s.towerShot(t,targets.find(e=>distance(e,{x:16.5,y:16.5})<.01)!,false);run(s,.7);expect(targets.filter(e=>e.hp<e.maxHp)).toHaveLength(MORTAR_TARGET_CAP[level-1]);}});
 it('precision, penetration and dual tags produce the approved combined damage',()=>{const s=sandbox(),t=s.buildings[0];s.buffs.crit=7;s.buffs.pierce=1;s.buffs.hunter=1;s.buffs.boss=1;s.attributes(t);const e=s.spawn('boss3',{x:20.5,y:16.5},15);const p=s.packet(t);expect(p.crit).toBe(true);s.hitEnemy(e,p);expect(e.maxHp-e.hp).toBeCloseTo(18*1.75*1.6*100/(100+25*.8));const skill=s.packet(t,true);expect(skill.crit).toBe(false);});
 it('foam slows without blocking and disappears with its source; boots remain terrain-bound',()=>{const s=sandbox();equip(s,'foam');s.use(0);expect(s.zones[0].kind).toBe('foam');expect(s.blocked.has(cell(s.player))).toBe(false);s.removeGear(s.gear[0]!);expect(s.zones).toHaveLength(0);equip(s,'boots');s.use(0);expect(s.speed).toBeCloseTo(5.12);s.player.x=16.5;s.player.y=2.5;s.input.y=-1;run(s,1);expect(s.player.y).toBeGreaterThanOrEqual(1.25);});
 it('player priority, invincibility idle, nearby buildings, resumed pursuit',()=>{const s=sandbox();s.buildings=[];s.reindex();const e=s.spawn('infantry',{x:18.5,y:16.5},1);run(s,.4);expect(e.x).toBeLessThan(18.5);equip(s,'invincible');s.use(0);const x=e.x;run(s,.5);expect(e.target).toBe(-1);expect(e.x).toBeCloseTo(x);const t=s.addBuilding('wall',e.x+.6,e.y,true);run(s,.3);expect(e.target).toBe(t.id);s.buildings=[];s.reindex();run(s,3.3);expect(s.invincible).toBe(false);run(s,.4);expect(e.target).toBe(0);});
 it('ordinary hit protection never removes target eligibility',()=>{const s=sandbox();s.god=false;s.damagePlayer(8);expect(s.invincible).toBe(false);s.damagePlayer(30);expect(s.player.hp).toBe(92);});
 it('taunt overrides player and honors immunity / boss resistance',()=>{const s=sandbox(),t=s.buildings[0];const e=s.spawn('infantry',{x:16.7,y:16.7},1),boss=s.spawn('boss1',{x:18,y:17},5);s.rebuildBuckets();s.taunt(t,4,2);expect(e.tauntUntil-s.time).toBe(2);expect(boss.tauntUntil-s.time).toBe(1);s.stun(boss,1);expect(boss.stunUntil).toBe(0);run(s,.1);expect(e.target).toBe(t.id);});
 it('enemy melee misses a player who moved out of range',()=>{const s=sandbox();s.god=false;s.buildings=[];s.reindex();const e=s.spawn('infantry',{x:17.1,y:16.5},1);run(s,.04);expect(e.wind).toBeGreaterThan(0);s.player.x=21;run(s,.4);expect(s.player.hp).toBe(100);expect(e.next).toBeGreaterThan(s.time);});
 it('zero overflow creates no secondary damage; valid overflow does not recurse',()=>{const s=sandbox();const e=s.spawn('infantry',{x:20,y:16},1),other=s.spawn('infantry',{x:20.5,y:16},1);s.rebuildBuckets();s.hitEnemy(e,{...packet(45),overflow:.5});expect(other.hp).toBe(45);const e2=s.spawn('infantry',{x:21,y:16},1);s.rebuildBuckets();s.hitEnemy(e2,{...packet(65),overflow:.5});expect(other.hp).toBe(35);});
 it('BOSS skills require range and invincibility cancels telegraphs',()=>{const s=sandbox();const e=s.spawn('boss1',{x:28,y:16.5},5);expect(s.bossSkill(e)).toBe(false);e.x=22;expect(s.bossSkill(e)).toBe(true);equip(s,'invincible');s.use(0);run(s,.1);expect(s.zones).toHaveLength(0);});
 it('rain produces exactly three ticks',()=>{const s=sandbox();s.god=false;s.buildings=[];s.player.x=16.5;s.player.y=16.5;s.zones.push({id:100,kind:'rain',x:16.5,y:16.5,radius:2,start:s.time,until:s.time+3,next:s.time+1,source:0,owner:0,dx:0,dy:0,travel:0,fired:true});run(s,3.1);expect(s.player.hp).toBe(76);});
});
describe('map, timing and terminal states',()=>{
 it('loads one authored effect and art variant for every cell of the fixed 32 by 32 map',()=>{expect(FIXED_MAP_ROWS).toHaveLength(SIZE);expect(FIXED_VARIANT_ROWS).toHaveLength(SIZE);expect(FIXED_MAP_ROWS.every(row=>row.length===SIZE)).toBe(true);expect(FIXED_VARIANT_ROWS.every(row=>/^[0-3]{32}$/.test(row))).toBe(true);const a=new WorldMap(),b=new WorldMap();expect(a.effects).toHaveLength(SIZE*SIZE);expect(a.variants).toHaveLength(SIZE*SIZE);expect([...a.tiles]).toEqual([...b.tiles]);expect([...a.elevation]).toEqual([...b.elevation]);expect([...a.ramps]).toEqual([...b.ramps]);expect([...a.variants]).toEqual([...b.variants]);expect(a.effects.every(Boolean)).toBe(true);expect(a.effects.map(e=>e.key)).toEqual(b.effects.map(e=>e.key));});
 it('uses the shared cell-effect table for movement, building, sight and air traversal',()=>{expect(CELL_EFFECTS.meadow).toMatchObject({walkable:true,buildable:true,moveFactor:1,blocksSight:false});expect(CELL_EFFECTS.mud).toMatchObject({walkable:true,buildable:false,moveFactor:.7});expect(CELL_EFFECTS.stone).toMatchObject({walkable:false,buildable:false,blocksGround:true,blocksSight:true});expect(CELL_EFFECTS.water).toMatchObject({walkable:false,buildable:false,blocksGround:true,blocksSight:false});expect(CELL_EFFECTS.cliff).toMatchObject({walkable:false,buildable:false,airPassable:true});expect(CELL_EFFECTS.ramp).toMatchObject({walkable:true,buildable:false,moveFactor:1});});
 it('allows walking across a ramp but rejects construction on either ramp mouth',()=>{const s=sandbox();s.player.x=13.5;s.player.y=12.5;expect(s.map.effectAt(s.player.x,s.player.y).key).toBe('ramp');expect(s.map.canStand(s.player.x,s.player.y)).toBe(true);expect(s.map.isBuildable(s.player.x,s.player.y)).toBe(false);const before=s.buildings.length;s.command('build');expect(s.buildings).toHaveLength(before);expect(s.messages.at(-1)?.text).toBe('坡道不可施工');});
 it('highland cliffs use blocked edge tiles while ramps remain passable',()=>{const map=new WorldMap();expect([...map.elevation].filter(Boolean)).toHaveLength(217);expect([...map.tiles].filter(v=>v===4)).toHaveLength(94);expect([...map.ramps].filter(Boolean)).toHaveLength(16);expect(map.terrain(10.5,7.5)).toBe(4);expect(map.canStand(9.8,7.5,.25)).toBe(false);expect(map.canStand(13.5,12.2,.25)).toBe(true);const s=sandbox();s.player.x=13.5;s.player.y=12.5;s.move(s.player,0,-1.2,.25,false);expect(s.player.y).toBeLessThan(11.5);expect(s.map.elevationAt(s.player.x,s.player.y)).toBe(1);});
 it('half-cell bosses traverse the southwest highland ramp instead of idling beside it',()=>{const s=sandbox();s.buildings=[];s.reindex();s.player.x=16.5;s.player.y=16.5;const e=s.spawn('boss1',{x:21.5,y:24.5},5),before=distance(e,s.player);e.skillAt=1e9;run(s,10);expect(distance(e,s.player)).toBeLessThan(before-2);expect(distance(e,{x:21.5,y:24.5})).toBeGreaterThan(2);});
 it('air units cross cliffs and share horizontal space only with the ground layer',()=>{const s=sandbox();s.buildings=[];s.reindex();const ground=s.spawn('infantry',{x:9.5,y:6.5},1),air=s.spawn('air',{x:9.5,y:6.5},6);expect(distance(ground,air)).toBe(0);s.move(ground,1.2,0,ENEMIES.infantry.r,true);s.move(air,1.2,0,ENEMIES.air.r,true);expect(ground.x).toBeLessThan(10);expect(air.x).toBeGreaterThan(10.5);const wingmate=s.spawn('air',{x:air.x,y:air.y},6);expect(distance(air,wingmate)).toBeGreaterThanOrEqual(ENEMIES.air.r*2-.001);});
 it('air units ignore terrain and building colliders but retain normal target priority',()=>{const s=sandbox(),tower=s.buildings[0];const e=s.spawn('air',tower,6);expect(distance(e,tower)).toBe(0);s.player.x=28;s.player.y=28;s.updateEnemies(0);expect(e.target).toBe(tower.id);s.player.x=e.x;s.player.y=e.y+.6;s.updateEnemies(0);expect(e.target).toBe(0);s.move(e,-12,0,ENEMIES.air.r,true);expect(s.map.canFly(e.x,e.y,ENEMIES.air.r)).toBe(true);});
 it('weighted flow reaches cells behind blocked enclosures',()=>{const map=new WorldMap(),blocked=new Set<number>();for(let y=13;y<=19;y++)for(let x=13;x<=19;x++)if(x===13||x===19||y===13||y===19)blocked.add(y*SIZE+x);const costs=new Map([...blocked].map(id=>[id,7.333333]));const normal=flow(map,{x:16.5,y:16.5},blocked),weighted=flow(map,{x:16.5,y:16.5},blocked,costs);expect(normal[12*SIZE+16]).toBe(Infinity);expect(Number.isFinite(weighted[12*SIZE+16])).toBe(true);});
 it('all meadow and mud terrain belongs to the starting region',()=>{const s=sandbox(),f=flow(s.map,s.player,new Set());expect([...s.map.tiles].filter((v,i)=>(v===0||v===3)&&!Number.isFinite(f[i]))).toHaveLength(0);});
 it('uses dense stone, water, mud and cliff faces while preserving a clear starting camp',()=>{const map=new WorldMap(),counts=[0,0,0,0,0];for(const tile of map.tiles)counts[tile]++;expect(counts).toEqual([608,200,63,59,94]);for(let y=13;y<=19;y++)for(let x=13;x<=19;x++)expect(map.tiles[y*SIZE+x]).toBe(0);});
 it('mud permits movement at 70 percent speed but rejects construction',()=>{const s=sandbox();s.player.x=21.5;s.player.y=16.5;expect(s.map.terrain(s.player.x,s.player.y)).toBe(3);expect(s.map.canStand(s.player.x,s.player.y)).toBe(true);expect(s.map.moveFactor(s.player.x,s.player.y)).toBe(.7);s.input.x=1;run(s,.5);expect(s.player.x).toBeCloseTo(21.5+3.2*.7*.5,2);const before=s.buildings.length;s.command('build');expect(s.buildings).toHaveLength(before);});
 it('wave 2 spawns by time while old enemies survive, pause freezes clock',()=>{const s=new Simulation();s.start();s.god=true;s.buildings=[];s.reindex();run(s,10.1);expect(s.wave).toBe(1);expect(s.enemies.length).toBeGreaterThan(0);const first=s.enemies[0].id;s.time=44.95;run(s,.1);expect(s.wave).toBe(2);expect(s.enemies.some(e=>e.id===first)).toBe(true);expect(s.enemies.some(e=>e.wave===2)).toBe(true);s.paused=true;const time=s.time;run(s,5);expect(s.time).toBe(time);});
 it('runs 21 waves with a boss every third wave and the colossus as the finale',()=>{const s=new Simulation(),bossRows=s.batches.filter(b=>b.kinds.some(k=>ENEMIES[k].boss));expect(TOTAL_WAVES).toBe(21);expect(s.batches.flatMap(b=>b.kinds)).toHaveLength(977);expect(bossRows.map(b=>b.wave)).toEqual([3,6,9,12,15,18,21]);expect(bossRows.map(b=>b.kinds.find(k=>ENEMIES[k].boss))).toEqual(Object.values(BOSS_WAVES));expect(bossRows.at(-1)!.kinds.at(-1)).toBe('boss5');expect(ENEMIES.boss5).toMatchObject({name:'城塞巨像',hp:9000,armor:35,attack:44,r:.72,boss:true});expect(s.batches.filter(b=>b.wave===1)).toHaveLength(WAVE_BATCHES.early);expect(s.batches.filter(b=>b.wave===6)).toHaveLength(WAVE_BATCHES.late);expect(s.batches.at(-1)!.time).toBe(915);expect(WAVES.reduce((sum,w)=>sum+w.reduce((a,b)=>a+b,0),0)).toBe(970);});
 it('introduces flying raiders from wave six without changing the configured total',()=>{expect(WAVES.slice(0,5).every(w=>w[4]===0)).toBe(true);expect(WAVES.slice(5).every(w=>w[4]>0)).toBe(true);expect(WAVES.reduce((sum,w)=>sum+w[4],0)).toBe(127);});
 it('blocked spawn never drops a scheduled batch',()=>{const s=sandbox();s.batches=[{time:0,wave:1,kinds:['infantry'],point:{x:17.5,y:16.5},done:false,retry:-100}];s.time=-.01;run(s,.1);expect(s.batches[0].done).toBe(false);expect(s.batches[0].retry).toBeGreaterThan(s.time);run(s,2.2);expect(s.batches[0].done).toBe(true);expect(s.enemies).toHaveLength(1);});
 it('does not win until wave 21 batches and enemies are gone; death wins same-tick precedence',()=>{const s=sandbox();s.time=999;s.wave=21;const e=s.spawn('infantry',{x:24,y:24},21);run(s,.1);expect(s.state).toBe('playing');s.hitEnemy(e,packet(10000));run(s,.1);expect(s.state).toBe('won');const loser=sandbox();loser.god=false;loser.time=999;loser.player.hp=0;run(loser,.1);expect(loser.state).toBe('lost');});
 it('all level-four stats derive from the approved base attributes',()=>{const s=sandbox();s.player.x=16.5;s.player.y=16.5;for(const k of KEYS){const t=s.addBuilding(k,18.5,16.5,true);t.level=4;s.attributes(t);expect(t.maxHp).toBeCloseTo(TOWERS[k].hp*HP_SCALE[3]);expect(t.attack).toBeCloseTo(TOWERS[k].attack*DMG_SCALE[3]);}});
});


describe('continuous enemy priority',()=>{
 it('switches from a building during windup immediately and restarts the windup',()=>{const s=sandbox(),t=s.buildings[0];s.player.x=28;s.player.y=28;const e=s.spawn('infantry',{x:t.x+1,y:t.y},1);s.updateEnemies(0);expect(e.target).toBe(t.id);expect(e.wind).toBeGreaterThan(0);const hp=t.hp;s.time+=.1;s.player.x=e.x;s.player.y=e.y+.6;s.updateEnemies(0);expect(e.target).toBe(0);expect(e.wind).toBeCloseTo(s.time+ENEMIES.infantry.wind);expect(t.hp).toBe(hp);});
 it('updates priority while stunned and returns to player as taunt expires',()=>{const s=sandbox(),t=s.buildings[0];const e=s.spawn('infantry',{x:t.x+1,y:t.y},1);s.player.x=e.x;s.player.y=e.y+.6;e.stunUntil=10;e.taunt=t.id;e.tauntUntil=1;s.updateEnemies(0);expect(e.target).toBe(t.id);s.time=1;s.updateEnemies(0);expect(e.target).toBe(0);});
 it('preserves a valid building target against equal-priority candidates',()=>{const s=sandbox(),t=s.buildings[0];s.player.x=28;s.player.y=28;const e=s.spawn('archer',{x:t.x+2,y:t.y},1);e.target=t.id;s.addBuilding('wall',t.x+1,t.y+1,true);s.updateEnemies(0);expect(e.target).toBe(t.id);});
});

describe('physical collision volumes',()=>{
 it('places enemies without overlapping each other or a building',()=>{const s=sandbox();s.buildings=[];s.reindex();const t=s.addBuilding('wall',20.5,16.5,true),a=s.spawn('heavy',{x:20.5,y:16.5},1),b=s.spawn('boss4',{x:a.x,y:a.y},20);expect(s.circleHitsBuilding(a,ENEMIES[a.kind].r,t)).toBe(false);expect(s.circleHitsBuilding(b,ENEMIES[b.kind].r,t)).toBe(false);expect(distance(a,b)).toBeGreaterThanOrEqual(ENEMIES[a.kind].r+ENEMIES[b.kind].r-.001);});
 it('keeps a moving crowd separated while allowing the queue to advance',()=>{const s=sandbox();s.buildings=[];s.reindex();const enemies=[s.spawn('infantry',{x:20.5,y:16.5},1),s.spawn('heavy',{x:20.5,y:16.5},1),s.spawn('cavalry',{x:20.5,y:16.5},1)];const start=Math.max(...enemies.map(e=>e.x));for(let i=0;i<90;i++){s.tick(1/30);for(let a=0;a<enemies.length;a++)for(let b=a+1;b<enemies.length;b++)expect(distance(enemies[a],enemies[b])).toBeGreaterThanOrEqual(ENEMIES[enemies[a].kind].r+ENEMIES[enemies[b].kind].r-.003);}expect(Math.max(...enemies.map(e=>e.x))).toBeLessThan(start);});
 it('prevents enemies from entering a building collider while attacking it',()=>{const s=sandbox(),t=s.buildings[0];s.player.x=28;s.player.y=28;const e=s.spawn('heavy',{x:t.x+2,y:t.y},1);run(s,3);expect(s.circleHitsBuilding(e,ENEMIES[e.kind].r,t)).toBe(false);expect(s.edgeDistance(e,t,t.id)).toBeGreaterThanOrEqual(0);});
});

it('screenshot geometry: infantry keeps attacking tower at two cells, switches when player enters actual reach',()=>{const s=sandbox();s.buildings=[];s.reindex();const t=s.addBuilding('arrow',18.5,16.5,true);const e=s.spawn('infantry',{x:17.4,y:17.5},1);s.player.x=19.4;s.player.y=17.5;s.updateEnemies(0);expect(s.canHit(e,s.player,0)).toBe(false);expect(e.target).toBe(t.id);const hp=t.hp;s.player.x=18.5;s.updateEnemies(0);expect(s.canHit(e,s.player,0)).toBe(true);expect(e.target).toBe(0);s.time=e.wind;s.updateEnemies(0);expect(t.hp).toBe(hp);});

describe('local co-op pressure and targeting',()=>{
 it('scales wave timing and enemy count for one to three workers without the supply surcharge',()=>{const one=new Simulation(1),two=new Simulation(2),three=new Simulation(3),total=(s:Simulation)=>s.batches.reduce((n,b)=>n+b.kinds.length,0);expect([one.waveInterval,two.waveInterval,three.waveInterval]).toEqual([45,42,39]);expect([total(one),total(two),total(three)]).toEqual([977,1512,2045]);expect(one.batches.find(b=>b.wave===TOTAL_WAVES)!.time).toBeGreaterThan(three.batches.find(b=>b.wave===TOTAL_WAVES)!.time);});
 it('uses one shared team resource and never restores it over time',()=>{const s=new Simulation(3);s.start();run(s,12);expect(s.gold).toBe(120);expect(s.players.map(p=>p.gold)).toEqual([120,120,120]);s.players[1].selected='wall';s.command('build',1);expect(s.gold).toBe(100);expect(s.players.map(p=>p.gold)).toEqual([100,100,100]);run(s,20);expect(s.gold).toBe(100);});
 it('spawns against the nearest worker and immediately changes to a closer player in range',()=>{const s=new Simulation(3);s.start();s.buildings=[];s.reindex();s.players[0].x=10;s.players[0].y=10;s.players[1].x=16;s.players[1].y=16;s.players[2].x=24;s.players[2].y=24;const e=s.spawn('infantry',{x:17,y:16},1);expect(e.target).toBe(s.players[1].id);s.players[0].x=e.x;s.players[0].y=e.y+.6;s.updateEnemies(0);expect(e.target).toBe(s.players[0].id);});
 it('lets two workers build at the same time from the shared pool',()=>{const s=new Simulation(2);s.start();s.players[0].selected='wall';s.players[1].selected='wall';s.command('build',0);s.command('build',1);expect(s.players.every(p=>p.task?.type==='build')).toBe(true);expect(s.gold).toBe(80);expect(s.players.map(p=>p.gold)).toEqual([80,80]);expect(s.buildings.map(t=>t.owner)).toEqual([0,-2]);run(s,1.6);expect(s.players.every(p=>p.task===null)).toBe(true);expect(s.buildings.filter(t=>t.kind==='wall'&&t.progress===1)).toHaveLength(2);});
 it('lets a teammate repair another player building from the shared pool',()=>{const s=new Simulation(2);s.start();s.time=0;s.batches=[];s.god=true;const owner=s.players[0],repairer=s.players[1],t=s.addBuilding('arrow',repairer.x,repairer.y,true,owner.id);t.hp=90;s.command('repair',1);run(s,.5);expect(t.hp).toBeCloseTo(105);expect(s.gold).toBeCloseTo(118.333333);expect(owner.gold).toBeCloseTo(s.gold);expect(repairer.gold).toBeCloseTo(s.gold);});
 it('allows a living worker to spend shared points to revive a nearby teammate',()=>{const s=new Simulation(2);s.start();s.god=false;const rescuer=s.players[0],fallen=s.players[1];fallen.hp=0;rescuer.x=fallen.x;rescuer.y=fallen.y;s.setGold(80);s.command('context',0);expect(s.gold).toBe(0);expect(s.players.every(p=>p.gold===0)).toBe(true);expect(fallen.hp).toBe(50);expect(fallen.hurtUntil).toBe(s.time+1);});
 it('credits every tower kill to the shared team resource, experience and level',()=>{const s=new Simulation(2);s.start();s.time=0;s.batches=[];s.setXp(39);const t=s.addBuilding('arrow',18.5,16.5,true,s.players[1].id),e=s.spawn('infantry',{x:22,y:16.5},1);s.hitEnemy(e,{...packet(1000),source:t.id});expect(s.gold).toBe(120+ENEMIES.infantry.gold);expect(s.players.every(p=>p.gold===s.gold)).toBe(true);expect(s.players.map(p=>p.xp)).toEqual([43,43]);expect(s.players.map(p=>p.level)).toEqual([2,2]);});
 it('continues while one worker lives and loses only after the whole party falls',()=>{const s=new Simulation(3);s.start();s.god=false;s.players[0].hp=0;s.tick(1/30);expect(s.state).toBe('playing');for(const p of s.players)p.hp=0;s.tick(1/30);expect(s.state).toBe('lost');});
 it('does not revive a fallen worker when shared team XP causes a level up',()=>{const s=new Simulation(2);s.start();s.god=false;s.players[0].hp=0;s.setXp(39);const e=s.spawn('infantry',{x:24,y:24},1);s.hitEnemy(e,packet(1000));expect(s.players.map(p=>p.xp)).toEqual([43,43]);expect(s.players.map(p=>p.level)).toEqual([2,2]);expect(s.players[0].hp).toBe(0);expect(s.players[1].hp).toBe(100);});
 it('allows two players to join during preparation without granting resources',()=>{const s=new Simulation(1);s.start();s.setGold(77);expect(s.joinPlayer()).toBe(true);expect(s.batches[0].time).toBe(0);expect(s.batches.reduce((n,b)=>n+b.kinds.length,0)).toBe(1512);expect(s.gold).toBe(77);expect(s.joinPlayer()).toBe(true);expect(s.players).toHaveLength(3);expect(s.waveInterval).toBe(39);expect(s.batches.reduce((n,b)=>n+b.kinds.length,0)).toBe(2045);expect(s.players.every(p=>p.gold===77)).toBe(true);expect(s.joinPlayer()).toBe(false);});
 it('adds only the base multiplayer difference and advances future timings on a live join',()=>{const s=new Simulation(1);s.start();s.god=true;s.time=20;s.wave=1;for(const b of s.batches.filter(b=>b.wave===1))b.done=true;const nextBefore=s.nextWaveAt;expect(s.joinPlayer()).toBe(true);const reinforcement=s.batches.find(b=>b.wave===1&&!b.done);expect(reinforcement?.kinds).toHaveLength(4);expect(reinforcement?.time).toBe(22);expect(s.nextWaveAt).toBeLessThan(nextBefore);run(s,2.2);expect(s.enemies).toHaveLength(4);});
 it('round-trips an authoritative network snapshot for a remote player',()=>{const host=new Simulation(2);host.start();host.time=20;host.wave=1;host.players[1].x=18;host.players[1].selected='wall';host.spawn('heavy',{x:24,y:18},4);host.command('build',1);const wire=JSON.parse(JSON.stringify(host.networkState()));const guest=new Simulation();guest.applyNetworkState(wire,1);expect(guest.focusPlayer).toBe(1);expect(guest.snapshot().players).toEqual(host.snapshot().players);expect(guest.enemies[0].kind).toBe('heavy');expect(guest.atPlayer(1)?.kind).toBe('wall');expect(guest.blocked.size).toBe(host.blocked.size);});
});
