import {describe,it,expect} from 'vitest';
import {Simulation,type Packet} from '../src/sim';
import {ACTIVES,BUFFS,ENEMIES,HP_SCALE,DMG_SCALE,KEYS,SIZE,TOWERS,WAVES,type ActiveKind} from '../src/data';
import {cell,distance,flow,WorldMap} from '../src/map';
const run=(s:Simulation,seconds:number)=>{for(let i=0;i<Math.round(seconds*30);i++)s.tick(1/30);};
function sandbox(){const s=new Simulation();s.start();s.time=0;s.batches=[];s.god=true;return s;}
function equip(s:Simulation,kind:ActiveKind,slot=0){s.gear[slot]={id:s.serial++,kind,ready:-100,until:-100};}
const packet=(damage:number):Packet=>({damage,pierce:0,hunter:0,boss:0,overflow:0,source:1,crit:false});
describe('construction and progression',()=>{
 it('charges once, preserves interrupted progress, finishes with remaining HP ratio',()=>{const s=sandbox();s.command('build');const t=s.atPlayer()!;expect(s.player.gold).toBe(80);run(s,.9);const progress=t.progress;s.input.x=1;run(s,.2);expect(s.task).toBeNull();expect(t.progress).toBe(progress);s.input.x=0;s.player.x=t.x;s.player.y=t.y;t.hp=t.maxHp*.5;s.command('build');run(s,2.3);expect(t.progress).toBe(1);expect(t.hp/t.maxHp).toBeCloseTo(.5);expect(s.player.gold).toBe(80);});
 it('incoming damage does not cancel construction',()=>{const s=sandbox();s.god=false;s.command('build');s.damagePlayer(10);expect(s.task?.type).toBe('build');run(s,.5);expect(s.atPlayer()!.progress).toBeGreaterThan(0);});
 it('repair matches construction progress rate and charges actual restoration',()=>{const s=sandbox();const t=s.buildings[0];s.player.x=t.x;s.player.y=t.y;t.hp=90;s.command('repair');run(s,.5);expect(t.hp).toBeCloseTo(120);expect(s.player.gold).toBeCloseTo(118);run(s,1);expect(t.hp).toBeCloseTo(180);expect(s.player.gold).toBeCloseTo(114);});
 it('upgrade keeps HP ratio and attack/skill progress',()=>{const s=sandbox(),t=s.buildings[0];s.player.level=11;s.player.gold=1000;s.player.x=t.x;t.hp=90;t.shot=.3;t.skill=.4;s.command('upgrade');expect(t.hp).toBe(130.5);expect(t.maxHp).toBe(261);expect(t.shot).toBe(.3);expect(t.skill).toBe(.4);});
 it('validates river, occupancy, unlock and capacity',()=>{const s=sandbox();s.player.x=20.5;s.player.y=5.5;const old=s.buildings.length;s.command('build');expect(s.buildings.length).toBe(old);s.player.x=32.5;s.player.y=32.5;s.selected='mortar';s.command('build');expect(s.buildings.length).toBe(old);s.selected='arrow';s.spawn('infantry',s.player,1);s.command('build');expect(s.buildings.length).toBe(old);});
 it('life aura toggling does not heal and uses effective max life for repair',()=>{const s=sandbox(),t=s.buildings[0];t.hp=90;s.buffs.life=1;s.attributes(t);expect(t.hp).toBe(112.5);s.player.x=45;s.attributes(t);expect(t.hp).toBe(90);s.player.x=t.x;s.command('repair');run(s,1.6);expect(t.hp).toBe(225);expect(s.player.gold).toBeCloseTo(114);});
});
describe('equipment / buffs',()=>{
 it('contains every approved reward',()=>{expect(Object.keys(ACTIVES)).toHaveLength(9);expect(Object.keys(BUFFS)).toHaveLength(11);expect(new Simulation().rewardPool).toHaveLength(20);});
 it('full active slots do not stop buff pickup or drop old gear',()=>{const s=sandbox();equip(s,'build');equip(s,'repair',1);s.drop('power',s.player);s.pickup();expect(s.buffs.power).toBe(1);expect(s.gear.map(g=>g?.kind)).toEqual(['build','repair']);expect(s.swap).toBeNull();expect(s.drops).toHaveLength(0);});
 it('swapped gear persists on same tile with cooldown intact',()=>{const s=sandbox();equip(s,'boots');equip(s,'repair',1);s.use(0);const ready=s.gear[0]!.ready;s.drop('build',s.player);s.pickup();expect(s.swap).not.toBeNull();s.exchange(0);expect(s.gear[0]!.kind).toBe('build');expect(s.drops[0].kind).toBe('boots');expect(s.drops[0].gear!.ready).toBe(ready);expect(s.drops[0].gear!.until).toBeLessThan(s.time);s.pickup();s.exchange(0);s.use(0);expect(s.active('boots')).toBe(false);});
 it('ground drops occupy separate tiles without blocking construction',()=>{const s=sandbox();s.drop('power',s.player);s.drop('armor',s.player);expect(new Set(s.drops.map(cell)).size).toBe(2);s.command('build');expect(s.atPlayer()).toBeTruthy();});
 it('construction and repair equipment affect their own rates only',()=>{const s=sandbox();expect(s.buildRate).toBe(s.repairRate);equip(s,'build');s.use(0);expect(s.buildRate).toBe(2);expect(s.repairRate).toBe(1);equip(s,'repair',1);s.use(1);expect(s.repairRate).toBe(2);});
 it('repair and construction base efficiency remain equal at every player level',()=>{const s=sandbox();for(let level=1;level<=12;level++){s.player.level=level;expect(s.repairRate).toBeCloseTo(s.buildRate);}});
 it('instant repair pays for actual HP, refuses full HP and cannot be boosted by repair',()=>{const s=sandbox(),t=s.buildings[0];s.player.x=t.x;equip(s,'instant');equip(s,'repair',1);s.use(0);expect(s.gear[0]!.ready).toBe(-100);t.hp=100;s.use(1);s.use(0);expect(t.hp).toBeCloseTo(163);expect(s.player.gold).toBeCloseTo(115.8);});
 it('shield protects scaffold and disappears on unequip',()=>{const s=sandbox();s.command('build');const t=s.atPlayer()!;equip(s,'shield');s.use(0);expect(t.shield).toBeCloseTo(16.2);s.damageBuilding(t,10);expect(t.hp).toBe(54);s.removeGear(s.gear[0]!);expect(t.shield).toBe(0);});
 it('attack-speed effects add and skill resonance remains separate',()=>{const s=sandbox(),t=s.buildings[0];s.buffs.haste=1;s.buffs.resonance=1;equip(s,'overload');s.use(0);s.attributes(t);expect(t.interval).toBeCloseTo(.8/1.8);expect(t.skillInterval).toBeCloseTo(6.8);});
});
describe('enemy and combat behavior',()=>{
 it('a complete tower enclosure triggers real demolition rather than idle pathfinding',()=>{const s=sandbox();s.buildings=[];s.reindex();for(let y=31;y<=33;y++)for(let x=31;x<=33;x++)if(x!==32||y!==32)s.addBuilding('wall',x+.5,y+.5,true);s.spawn('heavy',{x:36.5,y:32.5},1);run(s,45);expect(s.stats.lost).toBeGreaterThan(0);});
 it('a player inside a tower can still be hit by an archer targeting the player',()=>{const s=sandbox();s.god=false;s.player.x=s.buildings[0].x;s.player.y=s.buildings[0].y;const e=s.spawn('archer',{x:36.5,y:32.5},1);s.enemyArrow(e,s.player);s.projectiles[0].target=0;run(s,.45);expect(s.player.hp).toBeLessThan(100);});
 it('weaker slow resumes after a shorter strong slow expires',()=>{const s=sandbox();const e=s.spawn('heavy',{x:45.5,y:45.5},1);s.slow(e,.35,3);s.slow(e,.5,1);run(s,.5);expect(e.slow).toBe(.5);run(s,.7);expect(e.slow).toBe(.65);});
 it('precision, penetration and dual tags produce the approved combined damage',()=>{const s=sandbox(),t=s.buildings[0];s.buffs.crit=7;s.buffs.pierce=1;s.buffs.hunter=1;s.buffs.boss=1;s.attributes(t);const e=s.spawn('boss3',{x:36.5,y:32.5},15);const p=s.packet(t);expect(p.crit).toBe(true);s.hitEnemy(e,p);expect(e.maxHp-e.hp).toBeCloseTo(18*1.75*1.6*100/(100+25*.8));const skill=s.packet(t,true);expect(skill.crit).toBe(false);});
 it('foam slows without blocking and disappears with its source; boots remain terrain-bound',()=>{const s=sandbox();equip(s,'foam');s.use(0);expect(s.zones[0].kind).toBe('foam');expect(s.blocked.has(cell(s.player))).toBe(false);s.removeGear(s.gear[0]!);expect(s.zones).toHaveLength(0);equip(s,'boots');s.use(0);expect(s.speed).toBeCloseTo(5.12);s.player.x=18.5;s.player.y=5.5;s.input.x=1;run(s,1);expect(s.player.x).toBeLessThan(19);});
 it('player priority, invincibility idle, nearby buildings, resumed pursuit',()=>{const s=sandbox();s.buildings=[];s.reindex();const e=s.spawn('infantry',{x:34.5,y:32.5},1);run(s,.4);expect(e.x).toBeLessThan(34.5);equip(s,'invincible');s.use(0);const x=e.x;run(s,.5);expect(e.target).toBe(-1);expect(e.x).toBeCloseTo(x);const t=s.addBuilding('wall',e.x+.6,e.y,true);run(s,.3);expect(e.target).toBe(t.id);s.buildings=[];s.reindex();run(s,3.3);expect(s.invincible).toBe(false);run(s,.4);expect(e.target).toBe(0);});
 it('ordinary hit protection never removes target eligibility',()=>{const s=sandbox();s.god=false;s.damagePlayer(8);expect(s.invincible).toBe(false);s.damagePlayer(30);expect(s.player.hp).toBe(92);});
 it('taunt overrides player and honors immunity / boss resistance',()=>{const s=sandbox(),t=s.buildings[0];const e=s.spawn('infantry',{x:32.7,y:32.7},1),boss=s.spawn('boss1',{x:34,y:33},5);s.rebuildBuckets();s.taunt(t,4,2);expect(e.tauntUntil-s.time).toBe(2);expect(boss.tauntUntil-s.time).toBe(1);s.stun(boss,1);expect(boss.stunUntil).toBe(0);run(s,.1);expect(e.target).toBe(t.id);});
 it('enemy melee misses a player who moved out of range',()=>{const s=sandbox();s.god=false;s.buildings=[];s.reindex();const e=s.spawn('infantry',{x:33.1,y:32.5},1);run(s,.04);expect(e.wind).toBeGreaterThan(0);s.player.x=37;run(s,.4);expect(s.player.hp).toBe(100);expect(e.next).toBeGreaterThan(s.time);});
 it('zero overflow creates no secondary damage; valid overflow does not recurse',()=>{const s=sandbox();const e=s.spawn('infantry',{x:36,y:32},1),other=s.spawn('infantry',{x:36.5,y:32},1);s.rebuildBuckets();s.hitEnemy(e,{...packet(45),overflow:.5});expect(other.hp).toBe(45);const e2=s.spawn('infantry',{x:37,y:32},1);s.rebuildBuckets();s.hitEnemy(e2,{...packet(65),overflow:.5});expect(other.hp).toBe(35);});
 it('BOSS skills require range and invincibility cancels telegraphs',()=>{const s=sandbox();const e=s.spawn('boss1',{x:50,y:32.5},5);expect(s.bossSkill(e)).toBe(false);e.x=37;expect(s.bossSkill(e)).toBe(true);equip(s,'invincible');s.use(0);run(s,.1);expect(s.zones).toHaveLength(0);});
 it('rain produces exactly three ticks',()=>{const s=sandbox();s.god=false;s.buildings=[];s.player.x=32.5;s.player.y=32.5;s.zones.push({id:100,kind:'rain',x:32.5,y:32.5,radius:2,start:s.time,until:s.time+3,next:s.time+1,source:0,owner:0,dx:0,dy:0,travel:0,fired:true});run(s,3.1);expect(s.player.hp).toBe(76);});
});
describe('map, timing and terminal states',()=>{
 it('weighted flow reaches cells behind blocked enclosures',()=>{const map=new WorldMap(),blocked=new Set<number>();for(let y=29;y<=35;y++)for(let x=29;x<=35;x++)if(x===29||x===35||y===29||y===35)blocked.add(y*SIZE+x);const costs=new Map([...blocked].map(id=>[id,7.333333]));const normal=flow(map,{x:32.5,y:32.5},blocked),weighted=flow(map,{x:32.5,y:32.5},blocked,costs);expect(normal[28*SIZE+32]).toBe(Infinity);expect(Number.isFinite(weighted[28*SIZE+32])).toBe(true);});
 it('all meadow and mud terrain belongs to the starting region',()=>{const s=sandbox(),f=flow(s.map,s.player,new Set());expect([...s.map.tiles].filter((v,i)=>(v===0||v===3)&&!Number.isFinite(f[i]))).toHaveLength(0);});
 it('uses dense stone, water and mud while preserving a clear starting camp',()=>{const map=new WorldMap(),counts=[0,0,0,0];for(const tile of map.tiles)counts[tile]++;expect(counts[1]).toBeGreaterThan(350);expect(counts[2]).toBeGreaterThan(170);expect(counts[3]).toBeGreaterThan(100);for(let y=29;y<=35;y++)for(let x=29;x<=35;x++)expect(map.tiles[y*SIZE+x]).toBe(0);});
 it('mud permits movement at 70 percent speed but rejects construction',()=>{const s=sandbox();s.player.x=28.5;s.player.y=19.5;expect(s.map.terrain(s.player.x,s.player.y)).toBe(3);expect(s.map.canStand(s.player.x,s.player.y)).toBe(true);expect(s.map.moveFactor(s.player.x,s.player.y)).toBe(.7);s.input.x=1;run(s,.5);expect(s.player.x).toBeCloseTo(28.5+3.2*.7*.5,2);const before=s.buildings.length;s.command('build');expect(s.buildings).toHaveLength(before);});
 it('wave 2 spawns by time while old enemies survive, pause freezes clock',()=>{const s=new Simulation();s.start();s.god=true;s.buildings=[];s.reindex();run(s,10.1);expect(s.wave).toBe(1);expect(s.enemies).toHaveLength(4);const first=s.enemies[0].id;s.time=44.95;run(s,.1);expect(s.wave).toBe(2);expect(s.enemies.some(e=>e.id===first)).toBe(true);expect(s.enemies.some(e=>e.wave===2)).toBe(true);s.paused=true;const time=s.time;run(s,5);expect(s.time).toBe(time);});
 it('all scheduled batches contain 924 regular enemies + 4 bosses',()=>{const s=new Simulation();expect(s.batches.flatMap(b=>b.kinds)).toHaveLength(928);expect(s.batches.at(-1)!.time).toBe(865);expect(WAVES.reduce((sum,w)=>sum+w.reduce((a,b)=>a+b,0),0)).toBe(924);});
 it('blocked spawn never drops a scheduled batch',()=>{const s=sandbox();s.batches=[{time:0,wave:1,kinds:['infantry'],point:{x:33.5,y:32.5},done:false,retry:-100}];s.time=-.01;run(s,.1);expect(s.batches[0].done).toBe(false);expect(s.batches[0].retry).toBeGreaterThan(s.time);run(s,2.2);expect(s.batches[0].done).toBe(true);expect(s.enemies).toHaveLength(1);});
 it('does not win until pending batches and enemies are gone; death wins same-tick precedence',()=>{const s=sandbox();s.time=899;s.wave=20;const e=s.spawn('infantry',{x:44,y:44},20);run(s,.1);expect(s.state).toBe('playing');s.hitEnemy(e,packet(10000));run(s,.1);expect(s.state).toBe('won');const loser=sandbox();loser.god=false;loser.time=899;loser.player.hp=0;run(loser,.1);expect(loser.state).toBe('lost');});
 it('all level-four stats derive from the approved base attributes',()=>{const s=sandbox();s.player.x=32.5;s.player.y=32.5;for(const k of KEYS){const t=s.addBuilding(k,34.5,32.5,true);t.level=4;s.attributes(t);expect(t.maxHp).toBeCloseTo(TOWERS[k].hp*HP_SCALE[3]);expect(t.attack).toBeCloseTo(TOWERS[k].attack*DMG_SCALE[3]);}});
});


describe('continuous enemy priority',()=>{
 it('switches from a building during windup immediately and restarts the windup',()=>{const s=sandbox(),t=s.buildings[0];s.player.x=45;s.player.y=45;const e=s.spawn('infantry',{x:t.x+1,y:t.y},1);s.updateEnemies(0);expect(e.target).toBe(t.id);expect(e.wind).toBeGreaterThan(0);const hp=t.hp;s.time+=.1;s.player.x=e.x;s.player.y=e.y+.6;s.updateEnemies(0);expect(e.target).toBe(0);expect(e.wind).toBeCloseTo(s.time+ENEMIES.infantry.wind);expect(t.hp).toBe(hp);});
 it('updates priority while stunned and returns to player as taunt expires',()=>{const s=sandbox(),t=s.buildings[0];const e=s.spawn('infantry',{x:t.x+1,y:t.y},1);s.player.x=e.x;s.player.y=e.y+.6;e.stunUntil=10;e.taunt=t.id;e.tauntUntil=1;s.updateEnemies(0);expect(e.target).toBe(t.id);s.time=1;s.updateEnemies(0);expect(e.target).toBe(0);});
 it('preserves a valid building target against equal-priority candidates',()=>{const s=sandbox(),t=s.buildings[0];s.player.x=45;s.player.y=45;const e=s.spawn('archer',{x:t.x+2,y:t.y},1);e.target=t.id;s.addBuilding('wall',t.x+1,t.y+1,true);s.updateEnemies(0);expect(e.target).toBe(t.id);});
});

describe('physical collision volumes',()=>{
 it('places enemies without overlapping each other or a building',()=>{const s=sandbox();s.buildings=[];s.reindex();const t=s.addBuilding('wall',36.5,32.5,true),a=s.spawn('heavy',{x:36.5,y:32.5},1),b=s.spawn('boss4',{x:a.x,y:a.y},20);expect(s.circleHitsBuilding(a,ENEMIES[a.kind].r,t)).toBe(false);expect(s.circleHitsBuilding(b,ENEMIES[b.kind].r,t)).toBe(false);expect(distance(a,b)).toBeGreaterThanOrEqual(ENEMIES[a.kind].r+ENEMIES[b.kind].r-.001);});
 it('keeps a moving crowd separated while allowing the queue to advance',()=>{const s=sandbox();s.buildings=[];s.reindex();const enemies=[s.spawn('infantry',{x:36.5,y:32.5},1),s.spawn('heavy',{x:36.5,y:32.5},1),s.spawn('cavalry',{x:36.5,y:32.5},1)];const start=Math.max(...enemies.map(e=>e.x));for(let i=0;i<90;i++){s.tick(1/30);for(let a=0;a<enemies.length;a++)for(let b=a+1;b<enemies.length;b++)expect(distance(enemies[a],enemies[b])).toBeGreaterThanOrEqual(ENEMIES[enemies[a].kind].r+ENEMIES[enemies[b].kind].r-.003);}expect(Math.max(...enemies.map(e=>e.x))).toBeLessThan(start);});
 it('prevents enemies from entering a building collider while attacking it',()=>{const s=sandbox(),t=s.buildings[0];s.player.x=45;s.player.y=45;const e=s.spawn('heavy',{x:t.x+2,y:t.y},1);run(s,3);expect(s.circleHitsBuilding(e,ENEMIES[e.kind].r,t)).toBe(false);expect(s.edgeDistance(e,t,t.id)).toBeGreaterThanOrEqual(0);});
});

it('screenshot geometry: infantry keeps attacking tower at two cells, switches when player enters actual reach',()=>{const s=sandbox();s.buildings=[];s.reindex();const t=s.addBuilding('arrow',26.5,20.5,true);const e=s.spawn('infantry',{x:25.4,y:21.5},1);s.player.x=27.4;s.player.y=21.5;s.updateEnemies(0);expect(s.canHit(e,s.player,0)).toBe(false);expect(e.target).toBe(t.id);const hp=t.hp;s.player.x=26.5;s.updateEnemies(0);expect(s.canHit(e,s.player,0)).toBe(true);expect(e.target).toBe(0);s.time=e.wind;s.updateEnemies(0);expect(t.hp).toBe(hp);});
