import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';

await fs.mkdir('qa',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const errors=[];
const context=async(name)=>{const c=await browser.newContext({viewport:{width:1280,height:800}}),p=await c.newPage();p.on('pageerror',e=>errors.push(`${name}: ${e.message}`));await p.goto('http://127.0.0.1:5186/?qa');await p.click('[data-action="online-menu"]');await p.fill('#account-name',name);return{c,p};};
const host=await context('房主甲');await host.p.click('[data-action="online-create"]');await host.p.waitForFunction(()=>window.siege.online()?.host===true);const hostInfo=await host.p.evaluate(()=>window.siege.online());assert.equal(hostInfo.host,true);assert.equal(hostInfo.slot,0);const code=hostInfo.code;await host.p.evaluate(()=>{const s=window.siege.sim();s.time=20;s.wave=1;for(const b of s.batches.filter(b=>b.wave===1))b.done=true;window.siege.refresh();});
const guest=await context('队友乙');await guest.p.fill('#room-input',code);await guest.p.click('[data-action="online-join"]');await guest.p.waitForFunction(()=>window.siege.online()?.connected&&window.siege.snapshot().playerCount===2);await host.p.waitForFunction(()=>window.siege.snapshot().playerCount===2);const joined2=await host.p.evaluate(()=>{const s=window.siege.sim();return{room:window.siege.online(),state:s.snapshot(),reinforcements:s.batches.filter(b=>b.wave===1&&!b.done).map(b=>b.kinds.length)};});assert.equal(joined2.state.waveInterval,42);assert.equal(joined2.state.batches,1439);assert.equal(joined2.room.roster.length,2);assert.deepEqual(joined2.reinforcements,[4]);assert.equal(joined2.state.players[0].id,0);
const guestBefore=await host.p.evaluate(()=>window.siege.snapshot().players[1].x);await guest.p.keyboard.down('KeyD');await guest.p.waitForTimeout(500);await guest.p.keyboard.up('KeyD');await host.p.waitForFunction(x=>window.siege.snapshot().players[1].x>x,guestBefore);const guestAfter=await host.p.evaluate(()=>window.siege.snapshot().players[1].x);assert.ok(guestAfter>guestBefore);
await guest.p.keyboard.press('KeyE');await host.p.waitForFunction(()=>window.siege.snapshot().players[1].task?.type==='build');const built=await host.p.evaluate(()=>window.siege.snapshot());assert.equal(built.player.gold,80);
const third=await context('队友丙');await third.p.fill('#room-input',code);await third.p.click('[data-action="online-join"]');await third.p.waitForFunction(()=>window.siege.online()?.connected&&window.siege.snapshot().playerCount===3);await host.p.waitForFunction(()=>window.siege.snapshot().playerCount===3);const joined3=await host.p.evaluate(()=>{const s=window.siege.sim();return{room:window.siege.online(),state:s.snapshot(),reinforcements:s.batches.filter(b=>b.wave===1&&!b.done).map(b=>b.kinds.length),focus:s.focusPlayer};});assert.equal(joined3.state.waveInterval,39);assert.equal(joined3.state.batches,1944);assert.equal(joined3.room.roster.length,3);assert.deepEqual(joined3.reinforcements,[5]);assert.ok(joined3.state.enemies>=4);assert.equal(joined3.focus,0);await host.p.screenshot({path:'qa/12-online-host.png'});await guest.p.screenshot({path:'qa/13-online-guest.png'});
const full=await context('满房测试');await full.p.fill('#room-input',code);await full.p.click('[data-action="online-join"]');await full.p.waitForSelector('.warning-text');const fullError=(await full.p.locator('.warning-text').textContent())?.trim();assert.ok(fullError);await host.c.close();await guest.p.waitForSelector('.warning-text');const hostLeft=(await guest.p.locator('.warning-text').textContent())?.trim();assert.match(hostLeft||'',/房主已离开/);
const missing=await context('错误房间测试');const missingCode=code==='ZZZZZZ'?'YYYYYY':'ZZZZZZ';await missing.p.fill('#room-input',missingCode);await missing.p.click('[data-action="online-join"]');await missing.p.waitForSelector('.warning-text');const missingError=(await missing.p.locator('.warning-text').textContent())?.trim();assert.ok(missingError);
const result={errors,code,joined2:{players:joined2.state.playerCount,interval:joined2.state.waveInterval,batches:joined2.state.batches,reinforcements:joined2.reinforcements,roster:joined2.room.roster.map(m=>m.name)},remoteMove:{before:guestBefore,after:guestAfter},remoteBuild:{gold:built.player.gold,task:built.players[1].task?.type},joined3:{players:joined3.state.playerCount,interval:joined3.state.waveInterval,batches:joined3.state.batches,reinforcements:joined3.reinforcements,focus:joined3.focus,roster:joined3.room.roster.map(m=>m.name)},roomFull:fullError,hostDisconnect:hostLeft,missingRoom:missingError};
await fs.writeFile('qa/online-report.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));await browser.close();if(errors.length)process.exitCode=1;
