import Phaser from 'phaser';
import {ACTIVES,BUFFS,ENEMIES,isActive,KEYS,REPAIR_COST,REVIVE_COST,SIZE,TOWERS,UPGRADE,XP,type RewardKind} from './data';
import {cell} from './map';
import {BattleScene} from './render';
import {Simulation} from './sim';
import {AudioBus} from './audio';
import {loadAccount,OnlineRoom,roomCode,saveAccountName} from './network';
import './style.css';
let sim=new Simulation();const audio=new AudioBus();let book=false,onlineMenu=false,onlineError='',overlayKey='',lastMini=0,lobbyPlayers:1|2|3=1,online:OnlineRoom|null=null;
const ui=document.querySelector<HTMLDivElement>('#ui')!;
 ui.innerHTML=`<div class="vignette"></div><header id="hud"><div class="identity"><span class="brandmark">⚒</span><div><strong>围城工匠</strong><small>THE LAST BUILDERS</small></div></div><div class="survival" id="party-health"></div><div class="economy"><span>◆ <b id="gold">120</b></span><small id="capacity">建筑 0 · P1 +1/2秒</small></div><div class="wave"><span id="wave-title">准备阶段</span><small id="wave-time">敌军抵达 10s</small></div><div class="header-actions"><button data-action="join" id="join" title="本机加入队友">+P2</button><button data-action="copy-room" id="room" title="复制联机房间码" hidden></button><button data-action="sound" id="sound" title="声音开关">♪</button><button data-action="book" title="战地手册">?</button><button data-action="pause" title="暂停 P">Ⅱ</button></div></header>
<aside class="map-panel" id="map-panel"><canvas id="minimap" width="144" height="144" aria-label="战场地图"></canvas><div><span id="clock">00:00</span><small id="count">0 敌军</small></div></aside><div id="buffs" class="buffs"></div><div id="boss-bars"></div><div id="messages" aria-live="polite"></div>
<div id="context" class="context"></div><div id="toolbar" class="toolbar"></div><div id="equipment" class="equipment"></div><div class="bottom-hint" id="bottom-hint"><kbd>WASD</kbd>移动 <span>·</span> <kbd>E</kbd>建造 <kbd>R</kbd>修复 <kbd>F</kbd>升级 <kbd>G</kbd>拾取</div>
<div id="mobile-stick"><i></i></div><div id="overlay"></div>`;
const $=(id:string)=>document.getElementById(id)!;
const setHTML=(id:string,html:string)=>{const node=$(id);if(node.innerHTML!==html)node.innerHTML=html;};
const escapeHTML=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const clock=(t:number)=>`${Math.floor(Math.max(0,t)/60).toString().padStart(2,'0')}:${Math.floor(Math.max(0,t)%60).toString().padStart(2,'0')}`;
const scene=new BattleScene(sim,refresh);
const game=new Phaser.Game({type:Phaser.AUTO,parent:'world',width:window.innerWidth,height:window.innerHeight,backgroundColor:'#263e31',antialias:true,powerPreference:'high-performance',scale:{mode:Phaser.Scale.RESIZE,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[scene],audio:{noAudio:true},input:{keyboard:true}});
function resetSceneNetwork(){scene.online=false;scene.remote=false;scene.localSlot=0;scene.moveTarget=undefined;scene.onOnlineInput=undefined;scene.onOnlineCommand=undefined;scene.onOnlineSelect=undefined;}
function begin(practice=false){audio.enable();online?.close();online=null;resetSceneNetwork();sim=new Simulation(lobbyPlayers);scene.sim=sim;scene.keys.clear();scene.touch={x:0,y:0};book=false;onlineMenu=false;overlayKey='__refresh__';if(practice)sim.practiceStart();else sim.start();refresh();}
function onlineInput(input:{x:number;y:number}){if(!online)return;if(online.host){const p=sim.players[online.slot];if(p)p.input=input;}else online.sendInput(input);}
function onlineCommand(action:Parameters<Simulation['command']>[0]){if(!online){sim.command(action);return;}sim.command(action,online.slot);if(!online.host)online.sendCommand(action);}
function onlineSelect(index:number){if(!online)return;const p=sim.players[online.slot];if(p){p.selected=KEYS[index];sim.focusPlayer=online.slot;}if(!online.host)online.sendSelect(index);}
function connectOnline(code:string,create:boolean){
 const account=loadAccount();online?.close();onlineError='';sim=new Simulation(1);sim.start();scene.sim=sim;scene.keys.clear();scene.touch={x:0,y:0};scene.moveTarget=undefined;scene.online=true;scene.remote=true;scene.localSlot=0;scene.onOnlineInput=onlineInput;scene.onOnlineCommand=onlineCommand;scene.onOnlineSelect=onlineSelect;book=false;onlineMenu=false;overlayKey='__online__';
 online=new OnlineRoom(code,account,create?'create':'join',{
  onWelcome(member){scene.localSlot=member.slot;scene.remote=!member.host;sim.focusPlayer=member.slot;sim.message(member.host?`房间 ${code} 已建立，等待其他账号加入`:`已作为P${member.slot+1}加入房间 ${code}`,'wave');online?.pump(sim,true);refresh();},
  onJoin(member){if(!online?.host)return;while(sim.players.length<=member.slot)sim.joinPlayer();const p=sim.players[member.slot];if(p)p.input={x:0,y:0};sim.focusPlayer=online.slot;sim.message(`${member.name}作为P${member.slot+1}实时加入，敌军压力已提高`,'wave');online.pump(sim,true);refresh();},
  onLeave(slot){const p=sim.players[slot];if(p)p.input={x:0,y:0};sim.message(`P${slot+1}已断线，佣工留在原地`,'bad');refresh();},
  onState(state){if(online?.host)return;const error=sim.reconcileNetworkState(state,online?.slot||0);if(online)online.correction=error;refresh();},
  onInput(slot,input){if(!online?.host)return;const p=sim.players[slot];if(p)p.input=input;},
  onCommand(slot,action){if(!online?.host)return;if(action.startsWith('exchange:'))sim.exchange(Number(action.split(':')[1]),sim.swap,slot);else sim.command(action as Parameters<Simulation['command']>[0],slot);sim.focusPlayer=online.slot;online.pump(sim,true);},
  onSelect(slot,index){if(!online?.host)return;const p=sim.players[slot];if(p)p.selected=KEYS[Math.max(0,Math.min(KEYS.length-1,index))];},
  onStatus(text,bad){if(bad&&online&&!online.connected){onlineError=text;online=null;resetSceneNetwork();sim=new Simulation();scene.sim=sim;onlineMenu=true;overlayKey='__connection_error__';refresh();return;}sim.message(text,bad?'bad':'info');refresh();}
 });refresh();
}
ui.addEventListener('click',event=>{const button=(event.target as HTMLElement).closest<HTMLElement>('[data-action]');if(!button)return;audio.enable();const action=button.dataset.action!;
 if(action==='start'||action==='restart'){begin();return;}if(action==='practice'){begin(true);return;}
 if(action==='party'){lobbyPlayers=Math.max(1,Math.min(3,Number(button.dataset.count))) as 1|2|3;overlayKey='__party__';refresh();return;}
 if(action==='online-menu'){onlineMenu=true;onlineError='';book=false;overlayKey='__online_menu__';refresh();return;}
 if(action==='online-back'){onlineMenu=false;overlayKey='';refresh();return;}
 if(action==='online-create'||action==='online-join'){const name=(document.querySelector<HTMLInputElement>('#account-name')?.value||'').trim();saveAccountName(name);const code=action==='online-create'?roomCode():(document.querySelector<HTMLInputElement>('#room-input')?.value||'').toUpperCase().replace(/[^A-Z2-9]/g,'');if(code.length!==6){const input=document.querySelector<HTMLInputElement>('#room-input');input?.setCustomValidity('请输入6位房间码');input?.reportValidity();return;}connectOnline(code,action==='online-create');return;}
 if(action==='copy-room'&&online){navigator.clipboard?.writeText(online.code);sim.message(`房间码 ${online.code} 已复制`);refresh();return;}
 if(action==='join'&&!online){sim.joinPlayer();refresh();return;}
 if(action==='menu'){online?.close();online=null;resetSceneNetwork();sim.state='menu';sim.paused=false;book=false;onlineMenu=false;overlayKey='';refresh();return;}
 if(action==='sound'){audio.muted=!audio.muted;refresh();return;}
 if(action==='book'){book=!book;if(sim.state==='playing'&&!online)sim.paused=book;scene.keys.clear();refresh();return;}
 if(action==='pause'){if(online&&!online.host){sim.message('只有房主可以暂停联机对局','bad');refresh();return;}if(sim.state==='playing'){sim.paused=!sim.paused;book=false;scene.keys.clear();online?.pump(sim,true);}refresh();return;}
 if(action==='tower'){if(!sim.paused){const index=Number(button.dataset.index);if(online)onlineSelect(index);else sim.focused.selected=KEYS[index];}refresh();return;}
 if(action==='swap'){const index=Number(button.dataset.index);sim.exchange(index,sim.swap,online?.slot??sim.focusPlayer);if(online&&!online.host)online.sendCommand(`exchange:${index}`);else online?.pump(sim,true);refresh();return;}
 if(action==='grant'){sim.grant(button.dataset.kind as RewardKind);refresh();return;}
 if(action==='practice-wave'&&sim.practice){const b=sim.batches.find(b=>!b.done);if(b){sim.time=Math.max(sim.time,b.time-2.1);}refresh();return;}
 onlineCommand(action as Parameters<Simulation['command']>[0]);online?.pump(sim,true);refresh();
});
function refresh(){online?.pump(sim);const playing=sim.state==='playing';if(playing&&!sim.paused&&!online)book=false;ui.classList.toggle('in-game',playing);ui.classList.toggle('paused',sim.paused);ui.classList.toggle('practice',sim.practice);ui.classList.toggle('online',!!online);
 const low=XP[sim.player.level-1],high=XP[sim.player.level]||low+1,xp=sim.player.level===12?100:(sim.player.xp-low)/(high-low)*100;setHTML('party-health',`<span class="small-label">队伍 <b>Lv.${sim.player.level} · ${sim.playerCount}人</b></span><div class="party-bars">${sim.players.map((p,i)=>{const member=online?.roster.find(m=>m.slot===i);return`<div class="party-bar ${i===sim.focusPlayer?'focused':''}" style="--worker:#${p.color.toString(16).padStart(6,'0')}" title="${member?.name||`P${i+1}`}"><b>P${i+1}</b><div class="hp-track"><i style="width:${Math.max(0,p.hp)}%"></i><span>${p.hp>0?`${Math.max(0,Math.ceil(p.hp))} / ${p.maxHp}`:'已阵亡'}</span></div></div>`;}).join('')}</div><div class="xp-track"><i style="width:${xp}%"></i></div>`);
 $('gold').textContent=Math.floor(sim.gold).toString();$('capacity').textContent=`建筑 ${sim.buildings.length} · 击杀获得建造点`;
 $('wave-title').textContent=sim.time<0?'准备阶段':`第 ${sim.wave.toString().padStart(2,'0')} / 20 波`;
 $('wave-time').textContent=sim.time<0?`敌军抵达 ${Math.ceil(-sim.time)}s`:sim.wave===20?'最终清场 · 消灭全部敌军':`下一波 ${Math.max(0,Math.ceil(sim.nextWaveAt-sim.time))}s`;
 $('clock').textContent=clock(sim.time);$('count').textContent=`${sim.enemies.length} 敌军`;$('sound').textContent=audio.muted?'♫̸':'♪';const join=$('join') as HTMLButtonElement,room=$('room') as HTMLButtonElement;join.hidden=!!online||sim.playerCount>=3;join.textContent=`+P${sim.playerCount+1}`;room.hidden=!online;room.textContent=online?`房间 ${online.code}`:'';
 setHTML('toolbar',KEYS.map((k,i)=>{const d=TOWERS[k],locked=sim.player.level<d.unlock;return `<button data-action="tower" data-index="${i}" class="tower-choice ${sim.focused.selected===k?'selected':''} ${locked?'locked':''}" title="${d.name}：${d.desc}\n建造${d.work}秒 · 生命${d.hp} · 护甲${d.armor}"><kbd>${i+1}</kbd><span class="tower-icon ${k}">${d.icon}</span><strong>${d.name}</strong><small>${locked?'Lv.'+d.unlock+' 解锁':'◆ '+d.cost}</small></button>`;}).join(''));
 setHTML('equipment',sim.gear.map((g,i)=>{const d=g?ACTIVES[g.kind]:null,remaining=g?Math.max(0,g.ready-sim.time,(sim.shared[g.kind]||-100)-sim.time):0;return `<button data-action="active${i}" class="gear ${g&&g.until>sim.time?'active':''}" title="${d?.desc||'击败BOSS后拾取主动装备'}"><kbd>${i===0?'Q':'X'}</kbd><span>${d?.icon||'+'}</span><div><strong>${d?.name||'空装备格'}</strong><small>${remaining>0?'冷却 '+Math.ceil(remaining)+'s':d?'可以使用':'BOSS掉落装备'}</small></div>${remaining>0?`<i style="height:${remaining/(d?.cd||1)*100}%"></i>`:''}</button>`;}).join(''));
 setHTML('buffs',Object.entries(sim.buffs).map(([k,n])=>{const d=BUFFS[k as keyof typeof BUFFS];return `<span title="${d.name} ×${n}：${d.desc}，持续整局">${d.icon}<small>${n!>1?n:''}</small></span>`;}).join(''));
 setHTML('messages',sim.messages.slice(-3).map(m=>`<div class="toast ${m.type}">${m.text}</div>`).join(''));
 const worker=sim.focused,t=sim.atPlayer(worker),fallen=sim.reviveTarget(worker),drop=sim.drops.find(d=>cell(d)===cell(worker));let context=`<div class="worker-focus" style="--worker:#${worker.color.toString(16).padStart(6,'0')}">P${sim.focusPlayer+1} 操作 · 队伍 ◆${Math.floor(sim.gold)}</div>`;
 if(fallen){context+=`<div class="context-title">P${sim.players.indexOf(fallen)+1} 已阵亡 <small>可救援</small></div><p>复活后恢复50%生命，并获得1秒受击保护。</p><button class="action" data-action="context">复活队友 <span>◆ ${REVIVE_COST}</span></button>`;}
 else if(drop){const d=isActive(drop.kind)?ACTIVES[drop.kind]:BUFFS[drop.kind];context+=`<div class="context-title"><span class="gold">${d.icon}</span> ${d.name} <small>${isActive(drop.kind)?'主动装备':'永久被动BUFF'}</small></div><p>${d.desc}</p><button class="action" data-action="pickup">${isActive(drop.kind)&&sim.gear.every(Boolean)?'拾取 / 选择替换':'拾取'}</button>`;}
 else if(t){const d=TOWERS[t.kind],owner=sim.players.findIndex(p=>p.id===t.owner);context+=`<div class="context-title">${d.name} <small>P${owner+1}建筑 · ${t.progress<1?'施工中':`等级 ${t.level}`} · ${Math.ceil(t.hp)}/${Math.round(t.maxHp)}</small></div>`;
  if(t.progress<1)context+=`<div class="work-track"><i style="width:${t.progress*100}%"></i></div><button class="action" data-action="build">${worker.task?'正在建造':'继续建造'} · ${((1-t.progress)*d.work/sim.buildRate).toFixed(1)}s</button>`;
  else{context+=`<div class="context-actions"><button class="action" data-action="repair">修复${sim.underAttack(worker)?'（受攻击减速50%）':''} <small>◆ ${((t.maxHp-t.hp)/t.maxHp*d.cost*REPAIR_COST).toFixed(1)}</small></button><button class="action" data-action="upgrade">${t.level===4?'已满级':`升级 ◆ ${Math.ceil(d.cost*UPGRADE[t.level])}`}</button></div>`;}
 }else{const d=TOWERS[worker.selected];context+=`<div class="context-title">${d.name}<small>${d.desc}</small></div><button class="action" data-action="build">原地建造 <span>◆ ${d.cost} · ${(d.work/sim.buildRate).toFixed(1)}s</span></button>`;}
 setHTML('context',context);
 setHTML('boss-bars',sim.enemies.filter(e=>ENEMIES[e.kind].boss).map(e=>`<div class="boss-hud"><strong>${ENEMIES[e.kind].name}</strong><div><i style="width:${e.hp/e.maxHp*100}%"></i></div><small>${Math.ceil(e.hp)} / ${e.maxHp}</small></div>`).join(''));
 const bossCount=sim.enemies.filter(e=>ENEMIES[e.kind].boss).length;$('boss-bars').style.top=window.innerWidth<=720?'140px':'110px';$('messages').style.top=bossCount?(window.innerWidth<=720?140:110)+bossCount*43+8+'px':(window.innerWidth<=720?'85px':'115px');
 $('bottom-hint').innerHTML=online?`<b>${online.connected?'联机中':'连接中'} · ${online.account.name} · P${online.slot+1}</b> <span>·</span> 右键移动 · 空格/左键智能操作 · <kbd>E/R/F/G</kbd>`:sim.practice?'<span class="practice-label">演练 · 无敌</span> · 右键移动 · 空格/左键智能操作 <button data-action="practice-wave">下一批敌军 →</button> <button data-action="book">装备补给 / 手册</button>':sim.playerCount===1?'右键或<kbd>WASD</kbd>移动 · 空格/左键建造或修理 <span>·</span> P2按<kbd>ENTER</kbd>本机加入':sim.playerCount===2?'<b>本机同屏</b> · P1可用鼠标/空格 · P2 <kbd>方向键</kbd> · P3按<kbd>O</kbd>加入':'<b>本机三人</b> · P1可用鼠标/空格 · P2 <kbd>方向键</kbd> · P3 <kbd>IJKL</kbd>';
 let key=book?'book':onlineMenu?'online':sim.state==='menu'?'menu':sim.state==='won'||sim.state==='lost'?sim.state:sim.paused?'pause':sim.swap!==null?'swap'+sim.swap:'';
 if(key!==overlayKey){overlayKey=key;renderOverlay(key);}
 if(performance.now()-lastMini>300){drawMini();lastMini=performance.now();}
 for(const event of sim.soundEvents.splice(0))audio.play(event);
}
function renderOverlay(key:string){const root=$('overlay');root.innerHTML='';root.className=key?'visible '+(key==='menu'?'menu-overlay':''):'';if(!key)return;
 if(key==='online'){const account=loadAccount();root.innerHTML=`<section class="modal online-lobby"><span class="eyebrow">ONLINE CO-OP</span><h2>跨设备联机</h2><p>每台设备使用自己的账号。创建房间后把6位房间码发给队友，最多3人可在战斗中实时加入。</p>${onlineError?`<p class="warning-text">${escapeHTML(onlineError)}</p>`:''}<label>账号昵称<input id="account-name" maxlength="16" value="${escapeHTML(account.name)}" autocomplete="nickname"></label><button class="primary" data-action="online-create">创建新房间</button><div class="room-join"><input id="room-input" maxlength="6" pattern="[A-Z2-9]{6}" placeholder="输入6位房间码" autocomplete="off"><button class="secondary" data-action="online-join">加入房间</button></div><small>本机账号ID：${account.id.slice(-8).toUpperCase()} · 房主断线后本局结束</small><button class="text-button" data-action="online-back">返回</button></section>`;}
 else if(key==='menu')root.innerHTML=`<section class="landing"><div class="edition"><span></span> 跨设备联机 / 本机1～3人 · 20波守城</div><h1>围城<br><em>工匠</em><b>THE LAST BUILDERS</b></h1><p class="intro">你们没有利刃。<br>共同筑起的阵地，就是武器。</p><p class="landing-note">不同设备可凭房间码实时加入。<br>本机模式仍可选择1～3名佣工。</p><div class="party-picker" role="group" aria-label="本机初始参战人数">${([1,2,3] as const).map(n=>`<button data-action="party" data-count="${n}" class="${lobbyPlayers===n?'selected':''}"><b>${n}</b><small>${n===1?'45秒 · 1.0倍':n===2?'42秒 · 1.55倍':'39秒 · 2.1倍'}</small></button>`).join('')}</div><div class="start-actions"><button class="primary" data-action="online-menu">跨设备联机 <span>↗</span></button><button class="secondary" data-action="start">本机开始</button><button class="secondary compact" data-action="practice">演练</button></div><div class="landing-footer"><span>约13～15分钟 / 最多3个账号</span><button data-action="book">查看战地手册 ↗</button></div></section><div class="landing-caption"><i>01 / 联机营地</i><strong>一人开局，队友随时加入。<br>每个账号控制一名工匠。</strong><span>右键移动 · 空格/左键智能操作 · Q/X主动</span></div>`;
 else if(key==='pause')root.innerHTML=`<section class="modal"><span class="eyebrow">TAKE A BREATH</span><h2>战场已暂停</h2><p>${online&&!online.host?'房主暂停了联机对局，请等待房主继续。':'计时、施工和敌军都在等你。'}</p>${online&&!online.host?'':`<button class="primary" data-action="pause">继续守城</button>`}<button class="secondary" data-action="book">战地手册${sim.practice?' / 装备补给':''}</button><button class="text-button" data-action="menu">返回营地</button></section>`;
 else if(key==='won'||key==='lost')root.innerHTML=`<section class="modal result"><span class="eyebrow">${sim.practice?'PRACTICE COMPLETE':key==='won'?'THE NIGHT IS OVER':'THE WALLS REMEMBER'}</span><h2>${key==='won'?'守城成功':'防线失守'}</h2><p>${key==='won'?'最后一名敌人倒下。你守住了这片土地。':'每一道防线，都是下一次胜利的经验。'}</p><div class="results"><div><b>${clock(sim.time)}</b><small>生存时间</small></div><div><b>${sim.wave}/20</b><small>抵达波次</small></div><div><b>${sim.stats.kills}</b><small>消灭敌军</small></div><div><b>${sim.stats.built}</b><small>完成建造</small></div></div><details class="result-details"><summary>查看战场记录</summary><p>等级 ${sim.player.level} · 建筑损失 ${sim.stats.lost} · 修复生命 ${Math.round(sim.stats.repaired)}<br>击杀收入 ${sim.stats.income} · 支出 ${sim.stats.spent.toFixed(1)} · 主动使用 ${sim.stats.actives}次</p>${KEYS.filter(k=>sim.stats.damage[k]>0).map(k=>`<div>${TOWERS[k].name}<span>${Math.round(sim.stats.damage[k])} 伤害</span></div>`).join('')}<p>主动：${sim.gear.filter(Boolean).map(g=>ACTIVES[g!.kind].name).join('、')||'无'}<br>祝福：${Object.keys(sim.buffs).map(k=>BUFFS[k as keyof typeof BUFFS].name).join('、')||'无'}</p></details>${online?'':`<button class="primary" data-action="restart">再次守城 ↗</button>`}<button class="text-button" data-action="menu">返回营地</button></section>`;
 else if(key.startsWith('swap')){const d=sim.drops.find(d=>d.id===sim.swap);if(d&&isActive(d.kind))root.innerHTML=`<section class="modal swap"><span class="eyebrow">FIELD EQUIPMENT</span><h2>选择要替换的装备</h2><p class="warning-text">战斗仍在继续。旧装备会留在脚下，可再次拾取。</p><div class="new-gear"><b>${ACTIVES[d.kind].icon} ${ACTIVES[d.kind].name}</b><p>${ACTIVES[d.kind].desc}</p></div>${sim.gear.map((g,i)=>`<button class="swap-choice" data-action="swap" data-index="${i}"><b>${g?ACTIVES[g.kind].name:'空格'}</b><small>${g?ACTIVES[g.kind].desc:''}</small><span>替换 →</span></button>`).join('')}<button class="text-button" data-action="cancel">保留原装备</button></section>`;}
 else if(key==='book')root.innerHTML=`<section class="modal book"><div class="book-head"><div><span class="eyebrow">FIELD MANUAL</span><h2>工匠的战地手册</h2></div><button data-action="book" class="close">×</button></div><div class="book-scroll"><div class="manual-grid"><article><h3>01 · 跨设备账号联机</h3><p>每台设备设置自己的昵称并获得独立账号ID。房主创建6位房间码，队友在其他设备输入房间码即可在准备阶段或战斗中加入；最多3个账号。</p></article><article><h3>02 · 联机操作</h3><p>每个账号只控制自己的佣工：WASD或鼠标右键移动，1～5选塔，空格或鼠标左键按脚下情况建造/续建/修理，E/R/F/G执行指定操作，Q/X使用主动装备。只有房主能暂停，房主断线则房间结束。</p></article><article><h3>03 · 本机同屏模式</h3><p>本机模式可开局选择1～3人：P1使用WASD、鼠标与空格，P2使用方向键与回车组合，P3使用IJKL与O/U/Y/H组合。此模式与跨设备房间相互独立。</p></article><article><h3>04 · 队伍建造点</h3><p>队伍以120建造点开局，所有击杀收入自动进入共享资源池；建造、升级、维修和复活均从该资源池扣除。建造点不会随时间恢复，新佣工加入也不会额外获得资源。</p></article><article><h3>05 · 协作与增压</h3><p>任何佣工都能修理任意己方建筑，费用由队伍共同承担；敌人锁定维修佣工且处于有效攻击距离，或已有敌方弹道飞向该佣工时，持续维修速度降低50%。靠近阵亡队友后可花费${REVIVE_COST}点使其以50%生命复活。</p></article><article><h3>06 · 战场规则</h3><p>敌军持续优先索敌玩家。完整修复耗时为新建2倍、费用为1级造价50%。1/2/3人波次间隔为45/42/39秒，敌军倍率为1.0/1.55/2.1。断崖不可通行，坡面连接高低地，空军无视地面限制。</p></article></div><h3 class="catalog-title">主动装备 · 9种</h3><div class="catalog">${Object.entries(ACTIVES).map(([k,d])=>`<article><span>${d.icon}</span><div><b>${d.name}</b><p>${d.desc} · 冷却${d.cd}秒</p></div>${sim.practice?`<button data-action="grant" data-kind="${k}">投放</button>`:''}</article>`).join('')}</div><h3 class="catalog-title">被动祝福 · 11种</h3><div class="catalog">${Object.entries(BUFFS).map(([k,d])=>`<article><span>${d.icon}</span><div><b>${d.name}</b><p>${d.desc}</p></div>${sim.practice?`<button data-action="grant" data-kind="${k}">投放</button>`:''}</article>`).join('')}</div></div></section>`;
}
function drawMini(){const c=$('minimap') as HTMLCanvasElement,ctx=c.getContext('2d')!,scale=c.width/SIZE;ctx.fillStyle='#233b30';ctx.fillRect(0,0,c.width,c.height);
 for(let i=0;i<sim.map.elevation.length;i++)if(sim.map.elevation[i]){ctx.fillStyle='#49664b';ctx.fillRect(i%SIZE*scale,Math.floor(i/SIZE)*scale,scale,scale);}
 for(let i=0;i<sim.map.tiles.length;i++){const t=sim.map.tiles[i];if(t){ctx.fillStyle=t===1?'#627268':t===2?'#487d7e':t===4?'#1d3026':'#756c49';ctx.fillRect(i%SIZE*scale,Math.floor(i/SIZE)*scale,scale,scale);}}
 ctx.fillStyle='#c2a76b';for(let i=0;i<sim.map.ramps.length;i++)if(sim.map.ramps[i])ctx.fillRect(i%SIZE*scale,Math.floor(i/SIZE)*scale,scale,scale);
 ctx.fillStyle='#e7cb8b';for(const b of sim.buildings)ctx.fillRect(b.x*scale-1,b.y*scale-1,2,2);
 for(const e of sim.enemies){ctx.fillStyle=ENEMIES[e.kind].air?'#9ed9db':'#dc8d79';ctx.fillRect(e.x*scale-1,e.y*scale-1,ENEMIES[e.kind].boss?4:ENEMIES[e.kind].air?2.2:1.5,ENEMIES[e.kind].boss?4:ENEMIES[e.kind].air?2.2:1.5);}
 ctx.fillStyle='#a4e2d2';for(const d of sim.drops)ctx.fillRect(d.x*scale-1,d.y*scale-1,3,3);
 for(const p of sim.players){ctx.fillStyle='#'+p.color.toString(16).padStart(6,'0');ctx.beginPath();ctx.arc(p.x*scale,p.y*scale,3,0,Math.PI*2);ctx.fill();}
}
const stick=$('mobile-stick');let pointer:number|null=null;function stickMove(e:PointerEvent){if(pointer!==e.pointerId)return;const r=stick.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/35,dy=(e.clientY-r.top-r.height/2)/35,n=Math.max(1,Math.hypot(dx,dy));scene.touch={x:dx/n,y:dy/n};(stick.firstElementChild as HTMLElement).style.transform=`translate(${dx/n*25}px,${dy/n*25}px)`;}
stick.addEventListener('pointerdown',e=>{pointer=e.pointerId;stick.setPointerCapture(pointer);stickMove(e);});stick.addEventListener('pointermove',stickMove);for(const name of ['pointerup','pointercancel'])stick.addEventListener(name,()=>{pointer=null;scene.touch={x:0,y:0};(stick.firstElementChild as HTMLElement).style.transform='';});
// Read-only state hook, plus explicit scenario controls only in dev/QA URLs.
const qa=new URLSearchParams(location.search).has('qa');
Object.assign(window,{siege:{snapshot:()=>sim.snapshot(),...(qa?{sim:()=>sim,begin,step:(seconds:number)=>{for(let i=0;i<seconds*30;i++)sim.tick(1/30);refresh();},refresh,online:()=>online?{code:online.code,connected:online.connected,host:online.host,slot:online.slot,roster:online.roster,snapshots:online.snapshots,correction:online.correction,rejections:online.rejections}:null,networkSend:(data:unknown)=>online?.send(data)}:{} )}});
refresh();
