import Phaser from 'phaser';
import {ENEMIES,isActive,KEYS,SIZE,TILE,TOWERS} from './data';
import {directionFrame,enemyAttackFrame,facingFromInput,loopFrame,walkingFrame,type Facing} from './facing';
import {distance,type Point} from './map';
import {Simulation,type Building,type Enemy,type Worker} from './sim';
export class BattleScene extends Phaser.Scene{
 sim:Simulation;world!:Phaser.GameObjects.Graphics;actors!:Phaser.GameObjects.Graphics;effects!:Phaser.GameObjects.Graphics;labels:Phaser.GameObjects.Text[]=[];workerLabels:Phaser.GameObjects.Text[]=[];
 mapArt?:Phaser.GameObjects.Image;
 mapArtX=0;mapArtWidth=SIZE*TILE;
 unitImages:Phaser.GameObjects.Image[]=[];unitIndex=0;
 workerFacing:Facing[]=['down','down','down'];
 workerMotion=new Map<number,{x:number;y:number;facing:Facing;movingUntil:number}>();
 enemyMotion=new Map<number,{x:number;y:number;facing:Facing;movingUntil:number}>();
 keys=new Set<string>();acc=0;onTick:()=>void;lastUI=0;touch={x:0,y:0};moveTarget?:Point;moveTargetSlot=0;
 online=false;remote=false;localSlot=0;onOnlineInput?:(input:{x:number;y:number})=>void;onOnlineCommand?:(action:Parameters<Simulation['command']>[0])=>void;onOnlineSelect?:(index:number)=>void;
 constructor(sim:Simulation,onTick:()=>void){super('battle');this.sim=sim;this.onTick=onTick;}
 preload(){this.load.image('fixed-map-art','assets/terrain/fixed-map-art.png');for(let player=1;player<=3;player++)this.load.spritesheet(`unit-worker-p${player}`,`assets/characters/animated/worker-p${player}.png`,{frameWidth:192,frameHeight:192});for(const action of ['walk','build','repair'])this.load.spritesheet(`unit-worker-p1-${action}-v2`,`assets/characters/animated/worker-p1-${action}-v2.png`,{frameWidth:160,frameHeight:160});for(const key of ['infantry','heavy','archer','cavalry','air','boss'])this.load.spritesheet(`unit-${key}`,`assets/characters/animated/enemy-${key}.png`,{frameWidth:192,frameHeight:192});}
 create(){this.world=this.add.graphics().setDepth(0);this.actors=this.add.graphics().setDepth(1);this.effects=this.add.graphics().setDepth(3);this.drawMap();
  this.input.keyboard!.on('keydown',(e:KeyboardEvent)=>{if(['INPUT','SELECT','TEXTAREA'].includes((e.target as HTMLElement)?.tagName))return;this.keys.add(e.code);if(e.repeat)return;
   if(['Space','Enter','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();
   const s=this.sim;if(s.state!=='playing')return;
   if(this.online){
    if(e.code==='Escape'){this.onOnlineCommand?.('cancel');this.keys.clear();this.onTick();return;}
    if(/^Digit[1-5]$/.test(e.code)){this.onOnlineSelect?.(Number(e.code.slice(-1))-1);this.onTick();return;}
    if(['KeyW','KeyA','KeyS','KeyD'].includes(e.code))this.moveTarget=undefined;
    const action:{[key:string]:Parameters<Simulation['command']>[0]}={KeyE:'build',KeyR:'repair',KeyF:'upgrade',KeyG:'pickup',KeyQ:'active0',KeyX:'active1',Space:'context'};if(action[e.code]){this.onOnlineCommand?.(action[e.code]);this.onTick();}return;
   }
   if(e.code==='KeyP'){s.paused=!s.paused;this.keys.clear();this.onTick();return;}
   if(e.code==='Escape'){if(s.swap!==null||s.task){s.command('cancel');}else s.paused=!s.paused;this.keys.clear();this.onTick();return;}
   if((e.code==='Enter'&&s.playerCount===1)||(e.code==='KeyO'&&s.playerCount===2)){s.joinPlayer();this.keys.clear();this.onTick();return;}
   if(/^Digit[1-5]$/.test(e.code)){s.players[0].selected=KEYS[Number(e.code.slice(-1))-1];s.focusPlayer=0;}
   const moveOwner:Record<string,number>={KeyW:0,KeyA:0,KeyS:0,KeyD:0,ArrowUp:1,ArrowLeft:1,ArrowDown:1,ArrowRight:1,KeyI:2,KeyJ:2,KeyK:2,KeyL:2};if(moveOwner[e.code]!==undefined&&moveOwner[e.code]<s.playerCount){s.focusPlayer=moveOwner[e.code];if(this.moveTargetSlot===moveOwner[e.code])this.moveTarget=undefined;}
   const cycles:Record<string,[number,number]>={BracketLeft:[1,-1],BracketRight:[1,1],KeyN:[2,-1],KeyM:[2,1]};const cycle=cycles[e.code];if(cycle&&cycle[0]<s.playerCount){const p=s.players[cycle[0]],i=KEYS.indexOf(p.selected);p.selected=KEYS[(i+cycle[1]+KEYS.length)%KEYS.length];s.focusPlayer=cycle[0];}
   const actions:Record<string,[number,Parameters<Simulation['command']>[0]]>={KeyE:[0,'build'],KeyR:[0,'repair'],KeyF:[0,'upgrade'],KeyG:[0,'pickup'],KeyQ:[0,'active0'],KeyX:[0,'active1'],Space:[0,'context'],Enter:[1,'build'],Slash:[1,'repair'],Period:[1,'upgrade'],Comma:[1,'pickup'],Semicolon:[1,'active0'],Quote:[1,'active1'],KeyO:[2,'build'],KeyU:[2,'repair'],KeyY:[2,'upgrade'],KeyH:[2,'pickup'],KeyV:[2,'active0'],KeyB:[2,'active1']};const action=actions[e.code];if(action&&action[0]<s.playerCount)s.command(action[1],action[0]);this.onTick();
  });this.input.keyboard!.on('keyup',(e:KeyboardEvent)=>this.keys.delete(e.code));
  window.addEventListener('blur',()=>{this.keys.clear();this.touch={x:0,y:0};this.moveTarget=undefined;if(this.online)this.onOnlineInput?.({x:0,y:0});else if(this.sim.state==='playing'){this.sim.paused=true;this.onTick();}});
  this.input.on('pointerdown',(pointer:Phaser.Input.Pointer)=>{if(this.sim.state!=='playing'||this.sim.paused)return;if(pointer.rightButtonDown()){const world=this.cameras.main.getWorldPoint(pointer.x,pointer.y);this.moveTarget={x:world.x/TILE,y:world.y/TILE};this.moveTargetSlot=this.online?this.localSlot:this.sim.focusPlayer;this.sim.focusPlayer=this.moveTargetSlot;this.onTick();return;}if(pointer.leftButtonDown()){if(this.online)this.onOnlineCommand?.('context');else this.sim.command('context',this.sim.focusPlayer);this.onTick();}});this.game.canvas.addEventListener('contextmenu',e=>e.preventDefault());
  this.cameras.main.setBounds(this.mapArtX,0,this.mapArtWidth,SIZE*TILE);this.cameras.main.setBackgroundColor('#263e31');this.resize();this.scale.on('resize',()=>this.resize());
 }
 resize(){const camera=this.cameras.main;camera.setZoom(this.scale.width<700?.78:1);}
 drawMap(){this.world.clear();this.mapArt?.destroy();const source=this.textures.get('fixed-map-art').getSourceImage() as HTMLImageElement;this.mapArtWidth=source.width;this.mapArtX=(SIZE*TILE-this.mapArtWidth)/2;this.mapArt=this.add.image(this.mapArtX,0,'fixed-map-art').setOrigin(0).setDepth(-1);}
 update(_time:number,delta:number){const s=this.sim;this.acc+=Math.min(delta/1000,.15);const applyTarget=(input:Point,index:number)=>{const p=s.players[index];if(input.x||input.y||!p||!this.moveTarget||this.moveTargetSlot!==index)return input;const dx=this.moveTarget.x-p.x,dy=this.moveTarget.y-p.y,gap=Math.hypot(dx,dy);if(gap<.12){this.moveTarget=undefined;return{x:0,y:0};}return{x:dx/gap,y:dy/gap};};if(this.online){let input={x:(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0),y:(this.keys.has('KeyS')?1:0)-(this.keys.has('KeyW')?1:0)};input.x=input.x||this.touch.x;input.y=input.y||this.touch.y;input=applyTarget(input,this.localSlot);if(s.players[this.localSlot])s.players[this.localSlot].input=input;this.onOnlineInput?.(input);}else{const controls=[['KeyA','KeyD','KeyW','KeyS'],['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'],['KeyJ','KeyL','KeyI','KeyK']];for(let i=0;i<s.players.length;i++){const [left,right,up,down]=controls[i];s.players[i].input=applyTarget({x:(this.keys.has(right)?1:0)-(this.keys.has(left)?1:0),y:(this.keys.has(down)?1:0)-(this.keys.has(up)?1:0)},i);}s.player.input={x:s.player.input.x||this.touch.x,y:s.player.input.y||this.touch.y};}
  while(this.acc>=1/30){if(this.remote)s.predictNetwork(1/30,this.localSlot);else s.tick(1/30);this.acc-=1/30;}
  const party=s.alivePlayers(),center=s.partyCenter(),spreadX=Math.max(...party.map(p=>Math.abs(p.x-center.x)),0)*TILE*2,spreadY=Math.max(...party.map(p=>Math.abs(p.y-center.y)),0)*TILE*2,base=this.scale.width<700?.78:1,fit=Math.min(base,(this.scale.width-180)/Math.max(600,spreadX+420),(this.scale.height-170)/Math.max(480,spreadY+360));this.cameras.main.setZoom(Math.max(.55,fit)).centerOn(center.x*TILE,center.y*TILE-30);this.draw();if(_time-this.lastUI>100){this.lastUI=_time;this.onTick();}
 }
 draw(){const s=this.sim,g=this.actors,f=this.effects;g.clear();f.clear();this.unitIndex=0;for(const image of this.unitImages)image.setVisible(false);for(const l of [...this.labels,...this.workerLabels])l.setVisible(false);if(this.enemyMotion.size>s.enemies.length+64){const active=new Set(s.enemies.map(e=>e.id));for(const id of this.enemyMotion.keys())if(!active.has(id))this.enemyMotion.delete(id);}let label=0;
  const text=(x:number,y:number,str:string,color='#fff0c7',size=13)=>{let t=this.labels[label];if(!t){t=this.add.text(x,y,str,{fontFamily:'Arial, Microsoft YaHei, sans-serif',fontSize:size,color,stroke:'#182921',strokeThickness:3}).setOrigin(.5).setDepth(4);this.labels.push(t);}t.setPosition(x,y).setText(str).setColor(color).setFontSize(size).setVisible(true);label++;};
  const view=this.cameras.main.worldView,visible=(p:{x:number;y:number},r=2)=>p.x*TILE>view.x-r*TILE&&p.x*TILE<view.right+r*TILE&&p.y*TILE>view.y-r*TILE&&p.y*TILE<view.bottom+r*TILE;
  for(const z of s.zones){if(!visible(z,8))continue;const x=z.x*TILE,y=z.y*TILE,r=z.radius*TILE;
   if(z.kind==='foam'){g.fillStyle(0x83d5ca,.18).fillCircle(x,y,r);g.lineStyle(2,0x98e0d5,.4).strokeCircle(x,y,r);for(let i=0;i<9;i++)g.lineStyle(1,0xc2ece2,.3).strokeCircle(x+Math.cos(i*2.4)*r*.65,y+Math.sin(i*2.4)*r*.65,9+i%3*4);}
   else if(z.kind==='charge'){const e=s.enemies.find(e=>e.id===z.owner);const ox=(e?.x??z.x)*TILE,oy=(e?.y??z.y)*TILE;g.lineStyle(36,0xf39b78,z.fired?.18:.22).lineBetween(ox,oy,ox+z.dx*6*TILE,oy+z.dy*6*TILE);g.lineStyle(2,0xffc7a7,.8).lineBetween(ox,oy,ox+z.dx*6*TILE,oy+z.dy*6*TILE);}
   else{const pulse=.12+Math.sin(s.time*14)*.045;g.fillStyle(z.fired?0xc56a52:0xe48468,pulse).fillCircle(x,y,r);g.lineStyle(2,0xffb192,.9).strokeCircle(x,y,r);if(!z.fired){const remaining=Math.max(0,z.start-s.time);text(x,y-10,remaining.toFixed(1)+'s','#ffc8a6',16);g.lineStyle(1,0xffc9ad,.5).lineBetween(x-r*.35,y-r*.35,x+r*.35,y+r*.35).lineBetween(x+r*.35,y-r*.35,x-r*.35,y+r*.35);}}
  }
  for(const b of s.batches)if(!b.done&&b.point&&s.time>=b.time-2){const p=b.point,x=p.x*TILE,y=p.y*TILE;g.lineStyle(2,0xdd8b76,.7).strokeCircle(x,y,TILE*(1+.2*Math.sin(s.time*8)));g.lineStyle(1,0xdd8b76,.3).strokeCircle(x,y,TILE*1.6);if(visible(p))text(x,y-48,'敌军集结','#edb19b',12);}
  const p=s.focused,px=p.x*TILE,py=p.y*TILE,cx=(Math.floor(p.x)+.5)*TILE,cy=(Math.floor(p.y)+.5)*TILE;if(this.moveTarget){const color=s.players[this.moveTargetSlot]?.color??p.color;f.lineStyle(2,color,.65).strokeCircle(this.moveTarget.x*TILE,this.moveTarget.y*TILE,8);f.lineStyle(1,color,.45).lineBetween(this.moveTarget.x*TILE-12,this.moveTarget.y*TILE,this.moveTarget.x*TILE+12,this.moveTarget.y*TILE).lineBetween(this.moveTarget.x*TILE,this.moveTarget.y*TILE-12,this.moveTarget.x*TILE,this.moveTarget.y*TILE+12);}
  if(s.state==='playing'){const occupied=s.atPlayer(p);g.fillStyle(occupied?0xe2c181:0xf2d69a,.055).fillRect(cx-21,cy-21,42,42);g.lineStyle(1.5,p.color,.8).strokeRect(cx-20,cy-20,40,40);
   const r=occupied?.range||TOWERS[p.selected].range;if(r){g.lineStyle(1,occupied?TOWERS[occupied.kind].color:TOWERS[p.selected].color,.17).strokeCircle(cx,cy,r*TILE);}
   if(Object.keys(s.buffs).length||s.active('overload'))for(const worker of s.alivePlayers())g.lineStyle(1,worker.color,.13).strokeCircle(worker.x*TILE,worker.y*TILE,5*TILE);
  }
  for(const d of s.drops){if(!visible(d))continue;const x=d.x*TILE,y=d.y*TILE,bob=Math.sin(s.time*3+d.id)*2;g.fillStyle(isActive(d.kind)?0xf1c96d:0x9fd5c8,.07).fillCircle(x,y,25);g.lineStyle(1,isActive(d.kind)?0xf1c96d:0x9fd5c8,.55).strokeCircle(x,y,15);g.fillStyle(isActive(d.kind)?0xd6a550:0x91c9b9).fillTriangle(x,y-11+bob,x-8,y+bob,x,y+10+bob).fillTriangle(x,y-11+bob,x+8,y+bob,x,y+10+bob);g.fillStyle(0xffe6a8).fillCircle(x-2,y-3+bob,2);}
  const pointer=this.input.activePointer,mouse=this.cameras.main.getWorldPoint(pointer.x,pointer.y);
  const hovered=this.input.manager.isOver? s.enemies.filter(e=>e.hp>0&&Math.hypot(e.x*TILE-mouse.x,e.y*TILE-12-mouse.y)<24).sort((a,b)=>distance(a,{x:mouse.x/TILE,y:mouse.y/TILE})-distance(b,{x:mouse.x/TILE,y:mouse.y/TILE}))[0]:undefined;
  if(hovered){const e=hovered,d=ENEMIES[e.kind],hit=s.canHit(e,p,p.id),color=hit?0xffa084:0xeac88d;
   g.lineStyle(2,color,.8).strokeCircle(e.x*TILE,e.y*TILE,(d.range+d.r+.25)*TILE);
   const target=s.target(e.target);if(target)g.lineStyle(2,0xffa084,.8).lineBetween(e.x*TILE,e.y*TILE,target.x*TILE,target.y*TILE);
   const reason=s.invincible?'玩家无敌':s.edgeDistance(e,p,p.id)>d.range?'所选玩家在射程外':!d.air&&!s.map.los(e,p)?'岩石遮挡':e.tauntUntil>s.time?'受到嘲讽':'所选玩家在射程内';
   const targetPlayer=s.playerForTarget(e.target),name=targetPlayer?`P${s.players.indexOf(targetPlayer)+1}`:e.target===-1?'无':TOWERS[s.buildings.find(t=>t.id===e.target)?.kind??'wall'].name;
   text(e.x*TILE,e.y*TILE-62,`${d.name} · 目标：${name}`,'#ffe3bd',12);
   text(e.x*TILE,e.y*TILE-45,`${reason} · 圆圈为对玩家攻击边界`,'#ffe3bd',11);
  }
  const entities:({type:'tower';v:Building}|{type:'enemy';v:Enemy}|{type:'player';v:Worker})[]=[...s.buildings.map(v=>({type:'tower' as const,v})),...s.enemies.filter(e=>visible(e)).map(v=>({type:'enemy' as const,v})),...s.players.map(v=>({type:'player' as const,v}))];entities.sort((a,b)=>(a.v.y+(a.type==='player'?.15:0))-(b.v.y+(b.type==='player'?.15:0)));
  for(const entity of entities){const v=entity.v;if(!visible(v))continue;if(entity.type==='tower'){this.tower(g,entity.v);const t=entity.v;if(t.hp<t.maxHp-.1||s.atPlayer()?.id===t.id||t.progress<1){this.bar(g,t.x*TILE-17,t.y*TILE-37,34,3,t.hp/t.maxHp,0x9fc5a2);if(t.progress<1)this.bar(g,t.x*TILE-17,t.y*TILE+24,34,3,t.progress,0xe6bb6e);}if(t.level>1)text(t.x*TILE,t.y*TILE+14,['','II','III','IV'][t.level-1],'#f4dcab',9);}
   else if(entity.type==='enemy'){const e=entity.v,d=ENEMIES[e.kind];this.enemyImage(e);if(e.slowUntil>s.time)g.lineStyle(1,0xa0e9ed,.75).strokeEllipse(e.x*TILE,e.y*TILE+12,27*(d.boss?1.5:1),9*(d.boss?1.5:1));if(d.boss){const top=e.y*TILE-(e.kind==='boss5'?88:d.cavalry?76:70);this.bar(g,e.x*TILE-30,top,60,4,e.hp/e.maxHp,0xdc826f);text(e.x*TILE,top-13,d.name,'#e8b19b',11);}else if(e.hp<e.maxHp)this.bar(g,e.x*TILE-12,e.y*TILE-(d.air?52:32),24,2,e.hp/e.maxHp,0xc48b79);}
   else this.workerImage(entity.v,s.players.indexOf(entity.v));
  }
  for(const b of s.buildings){if(!visible(b))continue;if(b.shield>0&&b.shieldUntil>s.time){f.lineStyle(2,0x9adfe3,.7).strokeRoundedRect(b.x*TILE-21,b.y*TILE-32,42,52,10);this.bar(f,b.x*TILE-17,b.y*TILE-42,34,2,Math.min(1,b.shield/(b.maxHp*.3)),0x9adfe3);}}
  for(const b of s.enemies){if(!visible(b))continue;if(b.wind>s.time){const target=s.target(b.target);if(target){f.lineStyle(1,0xf0b3a3,.5).lineBetween(b.x*TILE,b.y*TILE,target.x*TILE,target.y*TILE);}}if(b.tauntUntil>s.time)text(b.x*TILE+12,b.y*TILE-25,'⚑','#ceb1f4',12);if(b.stunUntil>s.time)text(b.x*TILE,b.y*TILE-27,'✦','#fff0a2',15);}
  for(const b of s.projectiles){if(!visible(b))continue;const x=b.x*TILE,y=b.y*TILE;
   if(b.kind==='mortar'){const height=Math.sin(Math.min(1,b.age/b.life)*Math.PI)*40;f.fillStyle(0x0d1d16,.3).fillEllipse(x,y,9,4);f.fillStyle(0xf2bf75).fillCircle(x,y-height,4);f.fillStyle(0xffe3a1).fillCircle(x-1,y-height-1,2);}
   else{const e=s.enemies.find(e=>e.id===b.target);const tx=b.kind==='enemy'?b.tx:(e?.x??b.tx),ty=b.kind==='enemy'?b.ty:(e?.y??b.ty),angle=Math.atan2(ty-b.y,tx-b.x);f.lineStyle(b.kind==='ice'?3:2,b.kind==='enemy'?0xf6b3a0:b.kind==='ice'?0xa2eff7:0xf2d795,.9).lineBetween(x,y,x-Math.cos(angle)*12,y-Math.sin(angle)*12);}
  }
  for(const v of s.visuals){if(!visible(v,4))continue;const x=v.x*TILE,y=v.y*TILE,a=1-v.age/v.life;
   if(v.kind==='number')text(x,y-22-v.age*25,v.text||'',v.color===0xff968a?'#ffa49c':'#ffe09c',12);
   else if(v.kind==='ring'){f.lineStyle(2,v.color,a*.65).strokeCircle(x,y,v.size*TILE*(.4+v.age/v.life*.6));}
   else if(v.kind==='arc'){f.lineStyle(2,v.color,a).lineBetween(x,y,v.tx!*TILE,v.ty!*TILE);}
   else{f.fillStyle(v.color,a*.35).fillCircle(x,y,v.size*TILE*(.2+v.age/v.life*.8));for(let i=0;i<5;i++){const r=v.size*TILE*v.age/v.life;f.fillStyle(v.color,a).fillCircle(x+Math.cos(i*1.3)*r,y+Math.sin(i*1.3)*r,2);}}
  }
  for(const worker of s.players)if(worker.task){const t=s.buildings.find(b=>b.id===worker.task!.id);if(t){const wx=worker.x*TILE,wy=worker.y*TILE,repairSlowed=worker.task.type==='repair'&&s.underAttack(worker);f.lineStyle(2,worker.color,.8).lineBetween(wx,wy-7,t.x*TILE,t.y*TILE);text(wx,wy-49,worker.task.type==='build'?'施工 '+Math.floor(t.progress*100)+'%':repairSlowed?'受攻击 · 修复速度−50%':'修复中',repairSlowed?'#ffb39f':'#f2d795',12);}}
 }
 bar(g:Phaser.GameObjects.Graphics,x:number,y:number,w:number,h:number,fraction:number,color:number){g.fillStyle(0x11231d,.9).fillRoundedRect(x-1,y-1,w+2,h+2,2);g.fillStyle(color).fillRect(x,y,w*Math.max(0,Math.min(1,fraction)),h);}
 unitImage(key:string,x:number,y:number,height:number,flip=false,frame=0,nominal=192){let image=this.unitImages[this.unitIndex++];if(!image){image=this.add.image(x,y,key,frame).setOrigin(.5,1);this.unitImages.push(image);}else image.setTexture(key,frame);const scale=height/nominal;image.setPosition(x,y).setScale(scale).setFlipX(flip).setAngle(0).setAlpha(1).clearTint().setDepth(1.2+y/(SIZE*TILE)*.4).setVisible(true);return image;}
 walkPose(image:Phaser.GameObjects.Image,facing:Facing,strength=1,phaseTime=this.sim.time){const gait=Math.sin(phaseTime*Math.PI*7),horizontal=facing==='left'||facing==='right';image.y-=Math.abs(gait)*2*strength;if(horizontal)image.x+=gait*.5*strength*(facing==='right'?1:-1);}
 enemyImage(e:Enemy){const s=this.sim,d=ENEMIES[e.kind],target=s.target(e.target),last=this.enemyMotion.get(e.id)??{x:e.x,y:e.y,facing:'down' as Facing,movingUntil:-Infinity},dx=e.x-last.x,dy=e.y-last.y,positionMoving=Math.hypot(dx,dy)>.0005,movingUntil=positionMoving?s.time+.14:last.movingUntil,moving=positionMoving||s.time<movingUntil,attack=enemyAttackFrame(s.time,e.next,e.wind,d.wind,d.interval);let facing=last.facing;if(attack!==null&&target)facing=facingFromInput({x:target.x-e.x,y:target.y-e.y},facing);else if(positionMoving)facing=facingFromInput({x:dx,y:dy},facing);this.enemyMotion.set(e.id,{x:e.x,y:e.y,facing,movingUntil});const heights:Record<string,number>={infantry:51,heavy:55,archer:52,cavalry:64,air:58,boss1:82,boss2:85,boss3:91,boss4:98,boss5:112},nominals:Record<string,number>={infantry:160,heavy:160,archer:160,cavalry:170,air:140,boss:165},key=d.boss?'boss':e.kind,phaseTime=s.time+e.id*.017,step=moving?walkingFrame(phaseTime,{x:1,y:0}):0,frame=attack===null?directionFrame(facing,step):8+attack,flip=attack!==null&&!!target&&target.x<e.x,image=this.unitImage(`unit-${key}`,e.x*TILE,e.y*TILE+18,heights[e.kind],flip,frame,nominals[key]);if(attack===null&&moving&&e.kind==='air')this.walkPose(image,facing,.7,phaseTime);if(attack===null&&moving&&e.kind!=='air'){const trail=facing==='right'?-1:facing==='left'?1:0;this.actors.fillStyle(0xcbb477,.3).fillEllipse(e.x*TILE+trail*10,e.y*TILE+16,step?8:4,2.6);}if(e.flash>s.time)image.setTintFill(0xffe1c5);}
 workerImage(p:Worker,index:number){const s=this.sim,x=p.x*TILE,y=p.y*TILE,last=this.workerMotion.get(p.id)??{x:p.x,y:p.y,facing:this.workerFacing[index],movingUntil:-Infinity},dx=p.x-last.x,dy=p.y-last.y,inputMoving=Math.hypot(p.input.x,p.input.y)>.001,positionMoving=Math.hypot(dx,dy)>.0005,direction=inputMoving?p.input:positionMoving?{x:dx,y:dy}:{x:0,y:0},facing=facingFromInput(direction,last.facing),movingUntil=positionMoving||inputMoving?s.time+.14:last.movingUntil,moving=!p.task&&p.hp>0&&(inputMoving||positionMoving||s.time<movingUntil),step=moving?walkingFrame(s.time,{x:1,y:0}):0,horizontal=facing==='left'||facing==='right';this.workerFacing[index]=facing;this.workerMotion.set(p.id,{x:p.x,y:p.y,facing,movingUntil});let texture=`unit-worker-p${index+1}`,frame=p.task?(p.task.type==='build'?8:12)+loopFrame(s.time,8,4):directionFrame(facing,step),flip=!!p.task&&facing==='left',nominal=index===0?123:160;if(index===0&&p.task){texture=`unit-worker-p1-${p.task.type}-v2`;frame=loopFrame(s.time,10,8);nominal=113;}else if(index===0&&moving&&horizontal){texture='unit-worker-p1-walk-v2';frame=loopFrame(s.time,10,8);flip=facing==='left';nominal=113;}const image=this.unitImage(texture,x,y+19,58,flip,frame,nominal);if(moving&&!horizontal)this.walkPose(image,facing,.55);if(moving){const trail=facing==='right'?-1:facing==='left'?1:0;this.actors.fillStyle(0xd6bd78,.32).fillEllipse(x+trail*11,y+15,step?9:5,3);}if(p.hp<=0)image.setTint(0x77736d).setAlpha(.72);if(s.time>=0&&p.hurtUntil>s.time)image.setTintFill(0xffd1bd);if(s.invincible)this.actors.lineStyle(2,0xf9e6b2,.7+Math.sin(s.time*8)*.2).strokeCircle(x,y-4,27);this.actors.fillStyle(0x16271f,.88).fillRoundedRect(x-15,y-49,30,13,4);this.actors.lineStyle(1.5,p.color,.9).strokeRoundedRect(x-15,y-49,30,13,4);this.labelWorker(x,y-42.5,index);if(p.hp<=0)this.textLabel(x,y+31,'待救援 ◆80','#ffe0a1',10);}
 tower(g:Phaser.GameObjects.Graphics,t:Building){const x=t.x*TILE,y=t.y*TILE,d=TOWERS[t.kind];g.fillStyle(0x10241b,.52).fillEllipse(x+3,y+16,42,15);
  if(t.progress<1){g.fillStyle(0x27372f).fillRoundedRect(x-17,y-15,34,32,3);g.fillStyle(0x8e7048).fillRect(x-14,y-12,28,27);g.lineStyle(4,0x4c3928).strokeRect(x-17,y-22,34,39).lineBetween(x-16,y-21,x+16,y+16).lineBetween(x+16,y-21,x-16,y+16);g.lineStyle(2,0xd5b16b).strokeRect(x-15,y-20,30,35);g.fillStyle(0xf0c563).fillRect(x-20,y-25,40,6);g.fillStyle(0x5b4933).fillCircle(x-12,y-22,2).fillCircle(x+12,y-22,2);return;}
  g.fillStyle(0x34463e).fillRoundedRect(x-20,y+2,40,19,4);g.fillStyle(0x778279).fillRoundedRect(x-18,y-1,36,13,3);g.lineStyle(1,0xb4b9a7,.52).lineBetween(x-15,y+2,x+15,y+2);g.fillStyle(0x273930).fillRect(x-14,y+12,28,6);
  if(t.kind==='wall'){g.fillStyle(0x544332).fillRect(x-17,y-18,34,24);g.lineStyle(7,0x503b29).lineBetween(x-15,y-17,x+15,y+7).lineBetween(x+15,y-17,x-15,y+7);g.lineStyle(3,0xc09a62).lineBetween(x-15,y-19,x+15,y+5).lineBetween(x+15,y-19,x-15,y+5);g.fillStyle(0xd9d0a9).fillTriangle(x-19,y-27,x-11,y-19,x-16,y-10).fillTriangle(x,y-28,x+6,y-19,x,y-11).fillTriangle(x+19,y-27,x+11,y-19,x+16,y-10);return;}
  if(t.kind==='arrow'){g.fillStyle(0x3a2e23).fillRoundedRect(x-13,y-20,26,30,3);g.fillStyle(0x886744).fillRect(x-10,y-18,20,28);g.fillStyle(0xc19a5f).fillRect(x-14,y-22,28,6);g.fillStyle(0x4a3828).fillRect(x-19,y-27,38,8);g.fillStyle(0xd3b879).fillRect(x-18,y-29,36,4);g.fillStyle(0x35281f).fillRect(x-10,y-10,5,18).fillRect(x+5,y-10,5,18);g.lineStyle(3,0x4d3725).lineBetween(x,y-39,x,y-20);g.lineStyle(4,d.color).lineBetween(x-14,y-35,x+14,y-27);g.lineStyle(1,0xf1dfad).lineBetween(x-14,y-35,x+11,y-37).lineBetween(x+11,y-37,x+14,y-27);}
  if(t.kind==='mortar'){g.fillStyle(0x4d4134).fillCircle(x,y-2,17);g.lineStyle(3,0xc49c65).strokeCircle(x,y-2,16);g.fillStyle(0x2a3531).fillRoundedRect(x-8,y-33,17,35,6);g.fillStyle(0x84938a).fillRoundedRect(x-6,y-32,13,31,5);g.fillStyle(0x162821).fillEllipse(x+1,y-32,13,7);g.fillStyle(0xd6c49b,.8).fillRect(x-5,y-27,12,3);}
  if(t.kind==='frost'){g.fillStyle(0x405b55).fillRect(x-11,y-16,22,27);g.fillStyle(0x8ca69a).fillTriangle(x-16,y-15,x,y-24,x+16,y-15);g.fillStyle(0x57aeba,.72).fillTriangle(x,y-47,x-12,y-29,x,y-14).fillTriangle(x,y-47,x+12,y-29,x,y-14);g.fillStyle(0xc5fff2,.8).fillTriangle(x,y-47,x-10,y-30,x,y-27);g.lineStyle(1,0xe5fff7,.7).lineBetween(x,y-43,x,y-19);}
  if(t.kind==='taunt'){g.fillStyle(0x453a34).fillRoundedRect(x-13,y-21,26,33,3);g.fillStyle(0x8d7763).fillRect(x-10,y-18,20,29);g.fillStyle(0xb5a58c).fillRect(x-15,y-24,30,7);g.lineStyle(4,0x4b3828).lineBetween(x,y-21,x,y-51);g.lineStyle(2,0xe1d0a2).lineBetween(x,y-22,x,y-50);g.fillStyle(0x9a6fc0).fillTriangle(x+2,y-49,x+23,y-41,x+2,y-31);g.fillStyle(0xe1c7f0).fillCircle(x+9,y-41,2);}
 }
 enemy(g:Phaser.GameObjects.Graphics,e:Enemy){const d=ENEMIES[e.kind],x=e.x*TILE,y=e.y*TILE,scale=d.boss?Math.max(1.55,d.r/.6*1.55):1,bob=Math.sin(this.sim.time*9+e.id)*1.1,color=e.flash>this.sim.time?0xffd7b2:d.color,slow=()=>{if(e.slowUntil>this.sim.time)g.lineStyle(1,0xa0e9ed,.75).strokeEllipse(x,y+12,27*scale,9*scale);};
  if(d.air){const lift=21+bob,wing=Math.sin(this.sim.time*13+e.id)*4;g.fillStyle(0x0d2019,.3).fillEllipse(x,y+13,30,10);g.lineStyle(1,0xa5ddd7,.2).lineBetween(x,y+7,x,y-lift+7);g.fillStyle(0x2b3235).fillTriangle(x-2,y-lift,x-22,y-lift-10-wing,x-10,y-lift+9).fillTriangle(x+2,y-lift,x+22,y-lift-10-wing,x+10,y-lift+9);g.fillStyle(color,.82).fillTriangle(x-5,y-lift,x-18,y-lift-6-wing,x-9,y-lift+5).fillTriangle(x+5,y-lift,x+18,y-lift-6-wing,x+9,y-lift+5);g.fillStyle(0x303b40).fillEllipse(x,y-lift,13,20);g.fillStyle(0xb8aea0).fillCircle(x,y-lift-9,4);g.fillStyle(0xe36f56).fillCircle(x-2,y-lift-10,1).fillCircle(x+2,y-lift-10,1);g.fillStyle(0x242d32).fillTriangle(x-5,y-lift-10,x-2,y-lift-17,x,y-lift-10).fillTriangle(x,y-lift-10,x+3,y-lift-17,x+5,y-lift-10);slow();return;}
  if(d.cavalry){g.fillStyle(0x102018,.48).fillEllipse(x,y+14,38*scale,13*scale);g.fillStyle(0x352d28).fillEllipse(x,y+3,31*scale,16*scale);g.fillStyle(0x74553c).fillEllipse(x,y,28*scale,14*scale);g.fillStyle(0x8c6848).fillEllipse(x+14*scale,y-3,10*scale,17*scale);g.fillStyle(0x2b2925).fillTriangle(x+14*scale,y-11*scale,x+12*scale,y-18*scale,x+17*scale,y-12*scale);g.lineStyle(4,0x302923).lineBetween(x-9*scale,y+6,x-11*scale,y+17).lineBetween(x+7*scale,y+6,x+10*scale,y+17);g.fillStyle(0x252c2c).fillRoundedRect(x-8*scale,y-14*scale+bob,15*scale,16*scale,3);g.fillStyle(color).fillTriangle(x-10*scale,y-11*scale+bob,x+9*scale,y-11*scale+bob,x+5*scale,y+3*scale);g.fillStyle(0xa6aaa0).fillCircle(x-1*scale,y-18*scale+bob,6*scale);g.fillStyle(0x4a5050).fillEllipse(x-1*scale,y-21*scale+bob,14*scale,8*scale);g.lineStyle(3,0xc6a06b).lineBetween(x+4*scale,y-8*scale,x-20*scale,y-25*scale);g.fillStyle(0xd9d0b5).fillTriangle(x-22*scale,y-27*scale,x-15*scale,y-24*scale,x-20*scale,y-20*scale);slow();return;}
  g.fillStyle(0x102018,.5).fillEllipse(x,y+12,25*scale,10*scale);
  if(e.kind==='archer'||e.kind==='boss2'){g.fillStyle(0x292d2c).fillRect(x-7*scale,y+2,5*scale,10*scale).fillRect(x+2*scale,y+2,5*scale,10*scale);g.fillStyle(color).fillTriangle(x,y-20*scale+bob,x-11*scale,y-4*scale+bob,x+10*scale,y-4*scale+bob);g.fillStyle(0x6f3f36).fillRoundedRect(x-8*scale,y-6*scale+bob,16*scale,15*scale,3);g.fillStyle(0xc7ad91).fillCircle(x,y-12*scale+bob,4*scale);g.lineStyle(3,0x533724).strokeEllipse(x+10*scale,y-2*scale,12*scale,29*scale);g.lineStyle(1,0xe3c78e).lineBetween(x+10*scale,y-17*scale,x+10*scale,y+13*scale);g.lineStyle(2,0xc59a60).lineBetween(x+2*scale,y-5*scale,x+16*scale,y-5*scale);if(d.boss)g.fillStyle(0x717b78).fillRect(x-7*scale,y-10*scale,14*scale,4*scale);slow();return;}
  if(d.boss){g.fillStyle(0x252b2c).fillRect(x-10*scale,y+1*scale,8*scale,14*scale).fillRect(x+2*scale,y+1*scale,8*scale,14*scale);g.fillStyle(0x242a2b).fillRoundedRect(x-13*scale,y-13*scale+bob,26*scale,24*scale,5);g.fillStyle(color).fillTriangle(x-14*scale,y-8*scale+bob,x+14*scale,y-8*scale+bob,x+10*scale,y+13*scale);g.fillStyle(0x555b59).fillRoundedRect(x-14*scale,y-14*scale+bob,28*scale,11*scale,4);g.fillStyle(0x89908a).fillCircle(x,y-17*scale+bob,8*scale);g.fillStyle(0x363d3e).fillRoundedRect(x-9*scale,y-22*scale+bob,18*scale,11*scale,4);g.fillStyle(0xe8b36c).fillTriangle(x-9*scale,y-20*scale,x-15*scale,y-31*scale,x-4*scale,y-23*scale).fillTriangle(x+9*scale,y-20*scale,x+15*scale,y-31*scale,x+4*scale,y-23*scale);g.fillStyle(0xef7156).fillRect(x-5*scale,y-19*scale+bob,3*scale,2*scale).fillRect(x+2*scale,y-19*scale+bob,3*scale,2*scale);g.lineStyle(5,0x805936).lineBetween(x+9*scale,y-4*scale,x+20*scale,y-24*scale);g.fillStyle(0x3d4544).fillRoundedRect(x+12*scale,y-31*scale,17*scale,13*scale,3);g.lineStyle(1,0xabb0a6).strokeRoundedRect(x+12*scale,y-31*scale,17*scale,13*scale,3);slow();return;}
  const heavy=e.kind==='heavy',bodyScale=heavy?1.18:1;g.fillStyle(0x292f2e).fillRect(x-8*bodyScale,y+3,6*bodyScale,11).fillRect(x+2*bodyScale,y+3,6*bodyScale,11);g.fillStyle(color).fillRoundedRect(x-9*bodyScale,y-9+bob,18*bodyScale,19,4);g.fillStyle(heavy?0x606966:0xa4453f).fillTriangle(x-10*bodyScale,y-5+bob,x+10*bodyScale,y-5+bob,x+7*bodyScale,y+8);g.fillStyle(0xc6aa8f).fillCircle(x,y-14+bob,6);g.fillStyle(0x4a5050).fillRoundedRect(x-8*bodyScale,y-20+bob,16*bodyScale,9,4);g.lineStyle(1,0xaeb4ab,.7).lineBetween(x-6*bodyScale,y-18+bob,x+6*bodyScale,y-18+bob);
  if(heavy){g.fillStyle(0x303938).fillRoundedRect(x-17,y-8,11,23,3);g.fillStyle(0x697473).fillRoundedRect(x-15,y-7,9,20,2);g.fillStyle(0xa84840).fillRect(x-13,y-3,5,12);g.fillStyle(0xb9c0b5).fillCircle(x-10.5,y+3,2.5);}else{g.fillStyle(0x4c3527).fillRoundedRect(x-15,y-5,9,19,2);g.fillStyle(0xa84840).fillRect(x-13,y-3,5,14);g.lineStyle(2,0xd5d1bd).strokeRoundedRect(x-15,y-5,9,19,2);}g.lineStyle(3,0xc9c6b2).lineBetween(x+8,y+5,x+15,y-13);g.fillStyle(0xd9d5c2).fillTriangle(x+15,y-17,x+18,y-10,x+12,y-12);slow();
 }
 worker(g:Phaser.GameObjects.Graphics,p:Worker,index:number){const s=this.sim,x=p.x*TILE,y=p.y*TILE,bob=p.input.x||p.input.y?Math.sin(s.time*14)*1.7:0,alive=p.hp>0,team=alive?p.color:0x66635d,flash=p.hurtUntil>s.time;g.fillStyle(0x091e17,.52).fillEllipse(x+2,y+14,30,12);
  if(s.invincible)g.lineStyle(2,0xf9e6b2,.7+Math.sin(s.time*8)*.2).strokeCircle(x,y-4,25);
  g.fillStyle(0x242d2b).fillRoundedRect(x-10,y+4,8,13,3).fillRoundedRect(x+2,y+4,8,13,3);g.fillStyle(0x171f1e).fillEllipse(x-6,y+16,10,5).fillEllipse(x+7,y+16,10,5);g.fillStyle(flash?0xffc1ad:team).fillRoundedRect(x-12,y-11+bob,24,22,5);g.fillStyle(0x263b3d).fillRoundedRect(x-7,y-9+bob,14,20,3);g.lineStyle(3,team).lineBetween(x-6,y-8+bob,x-6,y+8).lineBetween(x+6,y-8+bob,x+6,y+8);g.fillStyle(0x765638).fillRect(x-11,y+5+bob,22,5);g.fillStyle(0xd4aa7d).fillCircle(x,y-17+bob,7);
  // The hard hat is always safety yellow; team color lives on the vest and label.
  g.fillStyle(0x5a3f1d).fillRoundedRect(x-11,y-29+bob,22,14,7).fillRect(x-14,y-19+bob,28,5);g.fillStyle(alive?0xf2b93f:0x817665).fillRoundedRect(x-10,y-28+bob,20,12,6).fillRect(x-13,y-19+bob,26,4);g.fillStyle(alive?0xffdc69:0x9a9080).fillRect(x-2,y-29+bob,4,12);g.lineStyle(1,0xffeda4,.8).lineBetween(x-7,y-25+bob,x+5,y-27+bob);
  if(p.hp<=0){g.lineStyle(2,p.color,.55).strokeCircle(x,y-7,25);g.lineStyle(3,0xf1d38d,.9).lineBetween(x-6,y-8,x+6,y-8).lineBetween(x,y-14,x,y-2);}
  const swing=p.task?Math.sin(s.time*18)*8:0;g.fillStyle(0xd4aa7d).fillCircle(x+10,y-1,4);g.lineStyle(4,0x815d3d).lineBetween(x+10,y,x+20,y-12+swing);if(index===1){g.lineStyle(4,0x99aaa5).lineBetween(x+16,y-8+swing,x+23,y-16+swing);g.lineStyle(3,0xbfcac3).lineBetween(x+21,y-18+swing,x+27,y-14+swing).lineBetween(x+21,y-18+swing,x+22,y-24+swing);}else{g.fillStyle(index===2?0x596260:0x858d89).fillRoundedRect(x+14,y-18+swing,index===2?15:17,index===2?10:8,2);g.lineStyle(1,0xc5ccc3,.7).strokeRoundedRect(x+14,y-18+swing,index===2?15:17,index===2?10:8,2);}
  g.fillStyle(0x16271f,.88).fillRoundedRect(x-14,y-45,28,13,4);g.lineStyle(1.5,p.color,.9).strokeRoundedRect(x-14,y-45,28,13,4);this.labelWorker(x,y-38.5,index);if(p.hp<=0)this.textLabel(x,y+29,'待救援 ◆80','#ffe0a1',10);
 }
 textLabel(x:number,y:number,value:string,color:string,size:number){let t=this.labels.find(l=>!l.visible);if(!t){t=this.add.text(x,y,value,{fontFamily:'Arial',fontSize:size,color,stroke:'#182921',strokeThickness:2}).setOrigin(.5).setDepth(4);this.labels.push(t);}t.setText(value).setStyle({fontFamily:'Arial',fontSize:size,color,stroke:'#182921',strokeThickness:2}).setPosition(x,y).setVisible(true);}
 labelWorker(x:number,y:number,index:number){let t=this.workerLabels[index];if(!t){t=this.add.text(x,y,`P${index+1}`,{fontFamily:'Arial',fontSize:9,color:'#fff3d2',stroke:'#182921',strokeThickness:2}).setOrigin(.5).setDepth(4);this.workerLabels[index]=t;}t.setPosition(x,y).setVisible(true);}
}

